import { hasSupabaseEnv } from "@/lib/supabase/config";import { createClient } from "@/lib/supabase/server";import type { Station } from "@/types/database";
const demo:Station[]=[{id:"1",city:"Erzurum",name:"Yakutiye",slug:"erzurum-yakutiye",is_active:true},{id:"2",city:"Erzurum",name:"Aziziye",slug:"erzurum-aziziye",is_active:true},{id:"3",city:"Kayseri",name:"Melikgazi",slug:"kayseri-melikgazi",is_active:true}];
export async function getMyStations(){if(!hasSupabaseEnv())return demo;const supabase=await createClient();const{data,error}=await supabase.from("stations").select("id,city,name,slug,is_active").eq("is_active",true).is("deleted_at",null).order("city");if(error)return[];return data as Station[]}
export async function getProfile(){if(!hasSupabaseEnv())return{id:"demo",first_name:"Demo",last_name:"Kullanıcı",email:"demo@ornek.com",phone:null,address:null,emergency_phone:null,employee_number:null,avatar_url:null,status:"active",employment_start_date:null,employment_end_date:null};const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const{data}=await supabase.rpc("get_my_profile");return data?.[0]??null}
export async function getStation(slug:string){const stations=await getMyStations();return stations.find(station=>station.slug===slug)??null}
export async function hasAdminAccess(){if(!hasSupabaseEnv())return true;const supabase=await createClient();const{data,error}=await supabase.rpc("has_admin_access");return !error&&data===true}
export async function getMyRoles(){if(!hasSupabaseEnv())return[];const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return[];const{data:assignments}=await supabase.from("user_roles").select("role_id").eq("user_id",user.id);const ids=(assignments??[]).map(x=>x.role_id);if(!ids.length)return[];const{data}=await supabase.from("roles").select("name,slug").in("id",ids).eq("is_active",true).order("name");return data??[]}
export async function getDashboardContent(){if(!hasSupabaseEnv())return{tasks:[],announcements:[]};const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return{tasks:[],announcements:[]};const[tasks,announcements]=await Promise.all([supabase.from("tasks").select("id,title,status,station_id,created_at").eq("assignee_id",user.id).neq("status","completed").order("created_at",{ascending:false}).limit(3),supabase.from("announcements").select("id,title,body,station_id,created_at").order("created_at",{ascending:false}).limit(3)]);return{tasks:tasks.data??[],announcements:announcements.data??[]}}
export type NotificationItem={id:string;title:string;body:string|null;is_read:boolean;read_at:string|null;type:string;entity_type:string|null;entity_id:string|null;action_url:string|null;severity:string;created_at:string};
export async function getNotifications(options:{kind?:string;unread?:boolean}={}):Promise<NotificationItem[]>{if(!hasSupabaseEnv())return[];const supabase=await createClient();const{data}=await supabase.rpc("list_notifications",{kind_filter:options.kind??null,unread_only:options.unread??false,cursor_created:null,cursor_id:null,page_size:30});return(data??[]) as NotificationItem[]}
export async function getStationContent(slug:string){const station=await getStation(slug);if(!station)return null;if(!hasSupabaseEnv())return{station,announcements:[],tasks:[],personnel:[] as StationPersonnel[]};const supabase=await createClient();const[announcements,tasks,personnel]=await Promise.all([supabase.from("announcements").select("id,title,body,created_at").eq("station_id",station.id).order("created_at",{ascending:false}).limit(20),supabase.from("tasks").select("id,title,status,assignee_id,created_at").eq("station_id",station.id).order("created_at",{ascending:false}).limit(20),supabase.rpc("get_station_personnel",{target_station:station.id})]);return{station,announcements:announcements.data??[],tasks:tasks.data??[],personnel:((personnel.data??[]) as StationPersonnel[]).map(person=>({...person,id:person.user_id}))}}

type StationPersonnel={user_id:string;id:string;first_name:string;last_name:string;avatar_url:string|null;role_name:string|null;role_rank:number|null;phone:string|null};
