import { hasSupabaseEnv } from "@/lib/supabase/config";import { createClient } from "@/lib/supabase/server";import type { Station } from "@/types/database";
const demo:Station[]=[{id:"1",city:"Erzurum",name:"Yakutiye",slug:"erzurum-yakutiye",is_active:true},{id:"2",city:"Erzurum",name:"Aziziye",slug:"erzurum-aziziye",is_active:true},{id:"3",city:"Kayseri",name:"Melikgazi",slug:"kayseri-melikgazi",is_active:true}];
export async function getMyStations(){if(!hasSupabaseEnv())return demo;const supabase=await createClient();const{data,error}=await supabase.from("stations").select("id,city,name,slug,is_active").eq("is_active",true).is("deleted_at",null).order("city");if(error)return[];return data as Station[]}
export async function getProfile(){if(!hasSupabaseEnv())return{first_name:"Demo",last_name:"Kullanıcı",email:"demo@ornek.com",phone:null,employee_number:null,avatar_url:null,status:"active",created_at:new Date(0).toISOString()};const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const{data}=await supabase.from("profiles").select("first_name,last_name,email,phone,employee_number,avatar_url,status,created_at").eq("id",user.id).single();return data}
export async function getStation(slug:string){const stations=await getMyStations();return stations.find(station=>station.slug===slug)??null}
export async function hasAdminAccess(){if(!hasSupabaseEnv())return true;const supabase=await createClient();const{data,error}=await supabase.rpc("has_admin_access");return !error&&data===true}
export async function getMyRoles(){if(!hasSupabaseEnv())return[];const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return[];const{data:assignments}=await supabase.from("user_roles").select("role_id").eq("user_id",user.id);const ids=(assignments??[]).map(x=>x.role_id);if(!ids.length)return[];const{data}=await supabase.from("roles").select("name,slug").in("id",ids).eq("is_active",true).order("name");return data??[]}
export async function getDashboardContent(){if(!hasSupabaseEnv())return{tasks:[],announcements:[]};const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return{tasks:[],announcements:[]};const[tasks,announcements]=await Promise.all([supabase.from("tasks").select("id,title,status,station_id,created_at").eq("assignee_id",user.id).neq("status","completed").order("created_at",{ascending:false}).limit(3),supabase.from("announcements").select("id,title,body,station_id,created_at").order("created_at",{ascending:false}).limit(3)]);return{tasks:tasks.data??[],announcements:announcements.data??[]}}
export async function getNotifications(){if(!hasSupabaseEnv())return[];const supabase=await createClient();const{data}=await supabase.from("notifications").select("id,title,body,is_read,created_at").order("created_at",{ascending:false}).limit(30);return data??[]}
export async function getStationContent(slug:string){const station=await getStation(slug);if(!station)return null;if(!hasSupabaseEnv())return{station,announcements:[],tasks:[],personnel:[]};const supabase=await createClient();const[announcements,tasks,assignments]=await Promise.all([supabase.from("announcements").select("id,title,body,created_at").eq("station_id",station.id).order("created_at",{ascending:false}).limit(20),supabase.from("tasks").select("id,title,status,assignee_id,created_at").eq("station_id",station.id).order("created_at",{ascending:false}).limit(20),supabase.from("user_station_assignments").select("user_id").eq("station_id",station.id)]);const ids=(assignments.data??[]).map(a=>a.user_id);const personnel=ids.length?await supabase.from("profiles").select("id,first_name,last_name,status,avatar_url").in("id",ids).eq("status","active"):null;return{station,announcements:announcements.data??[],tasks:tasks.data??[],personnel:personnel?.data??[]}}
