import {createClient} from "@/lib/supabase/client";
const DB="aytemiz-doco-offline-v1",STORE="records";export type DraftKind="chat"|"operation"|"announcement"|"task_evidence"|"handover"|"checklist"|"issue";export type OfflineDraft={kind:DraftKind;stationId:string;value:Record<string,string>;updatedAt:number};type Stored=OfflineDraft&{key:string;userId:string;recordType:"draft"|"queue";idempotencyKey?:string;status?:"pending"|"failed"};
function database(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE)){const store=db.createObjectStore(STORE,{keyPath:"key"});store.createIndex("user","userId");store.createIndex("type","recordType")}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function userId(){const{data:{user}}=await createClient().auth.getUser();return user?.id??null}
export async function saveDraft(draft:OfflineDraft){const uid=await userId();if(!uid)return;const db=await database(),tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put({...draft,userId:uid,recordType:"draft",key:`${uid}:draft:${draft.kind}:${draft.stationId}`} satisfies Stored)}
export async function loadDraft(kind:DraftKind,stationId:string){const uid=await userId();if(!uid)return null;const db=await database();return new Promise<OfflineDraft|null>((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).get(`${uid}:draft:${kind}:${stationId}`);r.onsuccess=()=>resolve(r.result??null);r.onerror=()=>reject(r.error)})}
export async function removeDraft(kind:DraftKind,stationId:string){const uid=await userId();if(!uid)return;const db=await database();db.transaction(STORE,"readwrite").objectStore(STORE).delete(`${uid}:draft:${kind}:${stationId}`)}
export async function queueMutation(kind:string,stationId:string,value:Record<string,string>){const uid=await userId();if(!uid)return;const idempotencyKey=crypto.randomUUID(),db=await database();db.transaction(STORE,"readwrite").objectStore(STORE).put({key:`${uid}:queue:${idempotencyKey}`,userId:uid,recordType:"queue",kind:kind as DraftKind,stationId,value,updatedAt:Date.now(),idempotencyKey,status:"pending"} satisfies Stored)}
export async function pendingMutationCount(){const uid=await userId();if(!uid)return 0;const db=await database();return new Promise<number>((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).index("user").getAll(uid);r.onsuccess=()=>resolve((r.result as Stored[]).filter(x=>x.recordType==="queue"&&x.status==="pending").length);r.onerror=()=>reject(r.error)})}
export async function clearOfflineUserData(){const uid=await userId();if(!uid)return;const db=await database(),tx=db.transaction(STORE,"readwrite"),index=tx.objectStore(STORE).index("user"),range=IDBKeyRange.only(uid);index.openKeyCursor(range).onsuccess=e=>{const cursor=(e.target as IDBRequest<IDBCursor>).result;if(cursor){tx.objectStore(STORE).delete(cursor.primaryKey);cursor.continue()}}}
export async function clearAllOfflineData(){await new Promise<void>((resolve,reject)=>{const r=indexedDB.deleteDatabase(DB);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);r.onblocked=()=>resolve()})}
