import {createClient} from "@/lib/supabase/server";
import {getStation} from "@/lib/data";
export async function stationContext(slug:string){const station=await getStation(slug);if(!station)return null;const supabase=await createClient();return{station,supabase}}
export type Phase6Person={user_id:string;first_name:string;last_name:string;role_name:string|null};
export async function handoverData(slug:string){const context=await stationContext(slug);if(!context)return null;const[{data:shifts},{data:handovers},{data:personnel}]=await Promise.all([context.supabase.from("shifts").select("id,name,starts_at,ends_at").eq("is_active",true).order("sort_order"),context.supabase.from("shift_handovers").select("id,handover_date,status,general_note,next_shift_note,submitted_at,shift_id,shift_handover_items(section_key,condition,note),shift_handover_acknowledgements(user_id,acknowledged_at)").eq("station_id",context.station.id).is("deleted_at",null).order("handover_date",{ascending:false}).limit(20),context.supabase.rpc("get_station_personnel",{target_station:context.station.id})]);return{...context,shifts:shifts??[],handovers:handovers??[],personnel:(personnel??[]) as Phase6Person[]}}
export async function checklistData(slug:string,date:string){const context=await stationContext(slug);if(!context)return null;await context.supabase.rpc("ensure_checklist_runs",{target_station:context.station.id,target_date:date,target_shift:null});const{data:runs}=await context.supabase.from("checklist_runs").select("id,status,run_date,started_at,completed_at,checklist_templates(name,description),checklist_run_items(id,status,note,checklist_template_items(title,description,is_required,requires_note,requires_photo))").eq("station_id",context.station.id).eq("run_date",date).order("created_at");const normalized=(runs??[]).map(run=>({...run,checklist_templates:Array.isArray(run.checklist_templates)?run.checklist_templates[0]:run.checklist_templates,checklist_run_items:(run.checklist_run_items??[]).map(item=>({...item,checklist_template_items:Array.isArray(item.checklist_template_items)?item.checklist_template_items[0]:item.checklist_template_items}))}));return{...context,runs:normalized}}
export async function issueData(slug:string){const context=await stationContext(slug);if(!context)return null;const[{data:issues},{data:personnel}]=await Promise.all([context.supabase.from("station_issues").select("id,title,description,category,priority,status,assigned_to,opened_at,resolved_at,station_issue_events(id,event_type,body,created_at)").eq("station_id",context.station.id).is("deleted_at",null).order("opened_at",{ascending:false}).limit(40),context.supabase.rpc("get_station_personnel",{target_station:context.station.id})]);return{...context,issues:issues??[],personnel:(personnel??[]) as Phase6Person[]}}
export async function dailyReportData(slug:string,date:string){const context=await stationContext(slug);if(!context)return null;const[{data:summary},{data:notes}]=await Promise.all([context.supabase.rpc("get_station_operations",{target_station:context.station.id,target_date:date}),context.supabase.from("station_daily_report_notes").select("id,content,created_at,created_by").eq("station_id",context.station.id).eq("report_date",date).is("deleted_at",null).order("created_at",{ascending:false})]);return{...context,summary:(summary??{}) as Record<string,number>,notes:notes??[]}}
export async function operationsSummary(stationId:string){const supabase=await createClient();const{data}=await supabase.rpc("get_station_operations",{target_station:stationId,target_date:new Date().toISOString().slice(0,10)});return(data??{}) as Record<string,number>}
