"use server";
import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";import { createClient } from "@/lib/supabase/server";import { validateMediaFile } from "@/lib/media/validation";
const UUID=/^[0-9a-f]{8}-[0-9a-f-]{27}$/i;const val=(f:FormData,k:string,n=4000)=>String(f.get(k)??"").trim().slice(0,n);
function fail(path:string,message:string):never{redirect(`${path}?error=${encodeURIComponent(message)}`)}
export async function createTaskAction(form:FormData){const slug=val(form,"stationSlug",120),stationId=val(form,"stationId",36),assigneeIds=form.getAll("assigneeIds").map(String).filter(x=>UUID.test(x)),draft=form.get("intent")==="draft";const base=`/station/${slug}/tasks`;if(!UUID.test(stationId))fail(base,"Geçersiz istasyon.");const dueDate=val(form,"dueDate",30);if(!dueDate)fail(base,"Son tarih gerekli.");const supabase=await createClient();const{data,error}=await supabase.rpc("create_task",{target_station:stationId,task_title:val(form,"title",160),task_description:val(form,"description"),task_priority:val(form,"priority",20),target_due_date:new Date(dueDate).toISOString(),target_shift:val(form,"shiftId",36)||null,assignee_ids:draft?[]:assigneeIds,requires_evidence:form.get("evidenceRequired")==="on",required_evidence_type:val(form,"evidenceType",30)||"none",requires_review:form.get("reviewRequired")==="on",save_as_draft:draft});if(error||!data)fail(base,error?.message??"Görev oluşturulamadı.");revalidatePath(base);redirect(`${base}/${data}`)}
export async function startTaskAction(form:FormData){const slug=val(form,"stationSlug",120),taskId=val(form,"taskId",36),path=`/station/${slug}/tasks/${taskId}`;const supabase=await createClient();const{error}=await supabase.rpc("start_task",{target_task:taskId});if(error)fail(path,error.message);revalidatePath(path);redirect(`${path}?saved=started`)}
export async function completeTaskAction(form:FormData){const slug=val(form,"stationSlug",120),stationId=val(form,"stationId",36),taskId=val(form,"taskId",36),path=`/station/${slug}/tasks/${taskId}`;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const assetIds:string[]=[];for(const entry of form.getAll("photos")){if(!(entry instanceof File)||entry.size===0)continue;const checked=validateMediaFile(entry.name,entry.type,entry.size);if(!checked.ok)fail(path,checked.message);const storagePath=`tasks/${stationId}/${taskId}/${user.id}/${crypto.randomUUID()}.${checked.extension}`;const bytes=await entry.arrayBuffer();const digest=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(x=>x.toString(16).padStart(2,"0")).join("");const{error:uploadError}=await supabase.storage.from("operation-media").upload(storagePath,bytes,{contentType:entry.type,upsert:false});if(uploadError)fail(path,"Fotoğraf yüklenemedi.");const{data:asset,error:assetError}=await supabase.from("media_assets").insert({bucket:"operation-media",storage_path:storagePath,original_name:entry.name,safe_name:storagePath.split("/").at(-1),mime_type:entry.type,file_extension:checked.extension,size_bytes:entry.size,checksum_sha256:digest,station_id:stationId,owner_id:user.id,uploaded_by:user.id}).select("id").single();if(assetError||!asset)fail(path,"Medya kaydı oluşturulamadı.");assetIds.push(asset.id)}const completed=val(form,"completedAt",30);const{error}=await supabase.rpc("complete_task",{target_task:taskId,evidence_description:val(form,"description"),target_completed_at:completed?new Date(completed).toISOString():new Date().toISOString(),asset_ids:assetIds});if(error)fail(path,error.message);revalidatePath(path);redirect(`${path}?saved=completed`)}
export async function reviewTaskAction(form:FormData){const slug=val(form,"stationSlug",120),taskId=val(form,"taskId",36),path=`/station/${slug}/tasks/${taskId}`;const supabase=await createClient();const{error}=await supabase.rpc("review_task",{target_task:taskId,decision:val(form,"decision",10),rejection_reason:val(form,"reason",500)||null});if(error)fail(path,error.message);revalidatePath(path);redirect(`${path}?saved=reviewed`)}
export async function editEvidenceAction(form:FormData){const slug=val(form,"stationSlug",120),taskId=val(form,"taskId",36),evidenceId=val(form,"evidenceId",36),path=`/station/${slug}/tasks/${taskId}`,completed=val(form,"completedAt",30);const supabase=await createClient();const{error}=await supabase.rpc("edit_task_evidence",{target_evidence:evidenceId,new_description:val(form,"description"),new_completed_at:completed?new Date(completed).toISOString():new Date().toISOString()});if(error)fail(path,error.message);revalidatePath(path);redirect(`${path}?saved=evidence-edited`)}
export async function editTaskAction(form:FormData){const slug=val(form,"stationSlug",120),taskId=val(form,"taskId",36),path=`/station/${slug}/tasks/${taskId}`,due=val(form,"dueDate",30);const supabase=await createClient();const{error}=await supabase.rpc("edit_task",{target_task:taskId,new_title:val(form,"title",160),new_description:val(form,"description"),new_priority:val(form,"priority",20),new_due_date:new Date(due).toISOString(),new_shift:val(form,"shiftId",36)||null});if(error)fail(path,error.message);revalidatePath(path);redirect(`${path}?saved=edited`)}
export async function reopenTaskAction(form:FormData){await simpleTaskAction(form,"reopen_task","reopened")}
export async function deleteTaskAction(form:FormData){await simpleTaskAction(form,"delete_task","deleted")}
async function simpleTaskAction(form:FormData,rpc:"reopen_task"|"delete_task",saved:string){const slug=val(form,"stationSlug",120),taskId=val(form,"taskId",36),path=`/station/${slug}/tasks/${taskId}`;const supabase=await createClient();const{error}=await supabase.rpc(rpc,{target_task:taskId});if(error)fail(path,error.message);revalidatePath(`/station/${slug}/tasks`);if(rpc==="delete_task")redirect(`/station/${slug}/tasks?saved=${saved}`);redirect(`${path}?saved=${saved}`)}
