import Link from "next/link";
import {ArrowLeft} from "lucide-react";
import {notFound} from "next/navigation";
import {OfflineDraftBridge} from "@/components/offline-draft-bridge";
import {Badge,Button,Card,EmptyState,FileUploader,Input,PageHeader,Select,Textarea} from "@/components/ui/primitives";
import {checklistData} from "@/lib/phase6";
import {completeChecklistAction,createSourceTaskAction,updateChecklistItemAction} from "../operations-actions";

export default async function Checklists({params,searchParams}:{params:Promise<{stationSlug:string}>;searchParams:Promise<{date?:string;error?:string}>}){
  const {stationSlug}=await params,query=await searchParams,date=query.date??new Date().toISOString().slice(0,10),data=await checklistData(stationSlug,date);if(!data)notFound();
  return <main className="shell"><Link href={`/station/${stationSlug}`} className="back-link"><ArrowLeft size={18}/>İstasyona dön</Link><PageHeader eyebrow="Günlük operasyon" title="Checklistler" description="Vardiya işlerini hızlıca tamamlayın ve sorunları kayda alın."/><form className="date-filter"><Input name="date" type="date" defaultValue={date}/><Button>Göster</Button></form>{query.error?<p className="form-error">{query.error}</p>:null}<section className="grid gap-4">{data.runs.length?data.runs.map(run=>{const items=run.checklist_run_items??[],done=items.filter(item=>item.status!=="pending").length;return <Card key={run.id}><div className="card-row"><div><h2>{run.checklist_templates?.name??"Checklist"}</h2><p className="muted">{done} / {items.length} tamamlandı · %{items.length?Math.round(done/items.length*100):0}</p></div><Badge tone={run.status==="completed"?"success":"warning"}>{run.status}</Badge></div><div className="progress"><span style={{width:`${items.length?done/items.length*100:0}%`}}/></div>{items.map(item=>{const formId=`checklist-${item.id}`,title=item.checklist_template_items?.title??"Checklist maddesi";return <Card key={item.id}><form id={formId} action={updateChecklistItemAction} className="checklist-item" encType="multipart/form-data"><input type="hidden" name="stationSlug" value={stationSlug}/><input type="hidden" name="stationId" value={data.station.id}/><input type="hidden" name="itemId" value={item.id}/><strong>{title}</strong><small className="muted">{item.checklist_template_items?.is_required?"Zorunlu":"Opsiyonel"}{item.checklist_template_items?.requires_photo?" · Fotoğraf gerekli":""}</small><Select name="status" defaultValue={item.status}><option value="pending">Bekliyor</option><option value="completed">Tamamlandı</option><option value="skipped">Atlandı</option><option value="issue">Sorun var</option></Select><Textarea name="note" defaultValue={item.note??""} placeholder="Not" rows={2}/>{item.checklist_template_items?.requires_photo?<FileUploader name="media" accept="image/jpeg,image/png,image/webp"/>:null}<Button variant="secondary">Maddeyi kaydet</Button></form><OfflineDraftBridge formId={formId} kind="checklist" stationId={`${data.station.id}:${item.id}`}/>{item.status==="issue"?<form action={createSourceTaskAction}><input type="hidden" name="stationSlug" value={stationSlug}/><input type="hidden" name="source" value="checklist"/><input type="hidden" name="sourceId" value={item.id}/><input type="hidden" name="title" value={title}/><Button variant="secondary">Bu sorun için görev oluştur</Button></form>:null}</Card>})}<form action={completeChecklistAction} className="sticky-actions"><input type="hidden" name="stationSlug" value={stationSlug}/><input type="hidden" name="runId" value={run.id}/><Button>Checklisti tamamla</Button></form></Card>}):<EmptyState title="Bekleyen checklist bulunmuyor" description="Bu tarih ve istasyon için aktif bir şablon yok."/>}</section></main>;
}
