"use server";
import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {createClient} from "@/lib/supabase/server";import {validateFileSignature,validateMediaFile} from "@/lib/media/validation";import {dispatchEntityPush} from "@/lib/push/send";
const val=(form:FormData,key:string,max=4000)=>String(form.get(key)??"").trim().slice(0,max);const UUID=/^[0-9a-f]{8}-[0-9a-f-]{27}$/i;function fail(path:string,message:string):never{redirect(`${path}?error=${encodeURIComponent(message)}`)}
async function upload(form:FormData,stationId:string,entity:string){const supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)return[];const ids:string[]=[];for(const file of form.getAll("media")){if(!(file instanceof File)||!file.size)continue;const checked=validateMediaFile(file.name,file.type,file.size);if(!checked.ok)continue;const bytes=new Uint8Array(await file.arrayBuffer());if(!validateFileSignature(bytes,checked.extension))continue;const path=`phase6/${stationId}/${user.id}/${entity}/${crypto.randomUUID()}.${checked.extension}`;const{error}=await supabase.storage.from("operation-media").upload(path,bytes,{contentType:file.type});if(error)continue;const digest=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(x=>x.toString(16).padStart(2,"0")).join("");const{data}=await supabase.from("media_assets").insert({bucket:"operation-media",storage_path:path,original_name:file.name,safe_name:path.split("/").at(-1),mime_type:file.type,file_extension:checked.extension,size_bytes:file.size,checksum_sha256:digest,station_id:stationId,owner_id:user.id,uploaded_by:user.id,metadata:{entity_type:entity}}).select("id").single();if(data)ids.push(data.id)}return ids}
export async function saveHandoverAction(form:FormData){const slug=val(form,"stationSlug",120),base=`/station/${slug}/handover`,stationId=val(form,"stationId",36),sections=["general","market","forecourt","pumps","pos","lpg","technical","cleaning","stock","personnel"].map((key,index)=>({key,condition:val(form,`${key}Condition`,20)||"ok",note:val(form,`${key}Note`,1000),order:index})),supabase=await createClient();const{data:id,error}=await supabase.rpc("save_handover",{target_station:stationId,target_shift:val(form,"shiftId",36),target_date:val(form,"date",10),general_text:val(form,"generalNote"),next_text:val(form,"nextShiftNote"),items:sections,participant_ids:form.getAll("participants").map(String).filter(x=>UUID.test(x))});if(error||!id)fail(base,"Devir teslim kaydedilemedi.");if(val(form,"intent")==="submit"){const media=await upload(form,stationId,"handover");const result=await supabase.rpc("submit_handover",{target_handover:id,media_ids:media});if(result.error)fail(base,"Devir teslim gönderilemedi.");await dispatchEntityPush("handover",id)}revalidatePath(base);redirect(`${base}?saved=1`)}
export async function acknowledgeHandoverAction(form:FormData){const slug=val(form,"stationSlug",120),base=`/station/${slug}/handover`,supabase=await createClient();const{error}=await supabase.rpc("acknowledge_handover",{target_handover:val(form,"handoverId",36)});if(error)fail(base,"Okundu bilgisi kaydedilemedi.");revalidatePath(base)}
export async function updateChecklistItemAction(form:FormData){const slug=val(form,"stationSlug",120),base=`/station/${slug}/checklists`,stationId=val(form,"stationId",36),media=await upload(form,stationId,"checklist"),supabase=await createClient();const{error}=await supabase.rpc("update_checklist_item",{target_item:val(form,"itemId",36),new_status:val(form,"status",20),new_note:val(form,"note",1000),media_ids:media});if(error)fail(base,"Checklist maddesi güncellenemedi.");revalidatePath(base)}
export async function completeChecklistAction(form:FormData){const slug=val(form,"stationSlug",120),base=`/station/${slug}/checklists`,supabase=await createClient();const{error}=await supabase.rpc("complete_checklist",{target_run:val(form,"runId",36)});if(error)fail(base,"Zorunlu maddeleri tamamlayın.");revalidatePath(base)}
export async function createIssueAction(form:FormData){const slug=val(form,"stationSlug",120),base=`/station/${slug}/issues`,stationId=val(form,"stationId",36),media=await upload(form,stationId,"issue"),supabase=await createClient();const{data:id,error}=await supabase.rpc("create_issue",{target_station:stationId,issue_title:val(form,"title",160),issue_description:val(form,"description"),issue_category:val(form,"category",80),issue_priority:val(form,"priority",20),target_assignee:val(form,"assignee",36)||null,media_ids:media});if(error||!id)fail(base,"Arıza kaydı oluşturulamadı.");await dispatchEntityPush("issue",id);revalidatePath(base);redirect(`${base}?saved=1`)}
export async function issueEventAction(form:FormData){const slug=val(form,"stationSlug",120),base=`/station/${slug}/issues`,supabase=await createClient();const{error}=await supabase.rpc("add_issue_event",{target_issue:val(form,"issueId",36),event_body:val(form,"body",1000)});if(error)fail(base,"Not eklenemedi.");revalidatePath(base)}
export async function transitionIssueAction(form:FormData){const slug=val(form,"stationSlug",120),base=`/station/${slug}/issues`,supabase=await createClient();const{error}=await supabase.rpc("transition_issue",{target_issue:val(form,"issueId",36),new_status:val(form,"status",30),resolution_note:val(form,"note",1000)||null});if(error)fail(base,"Arıza durumu değiştirilemedi.");revalidatePath(base)}
export async function saveDailyNoteAction(form:FormData){const slug=val(form,"stationSlug",120),base=`/station/${slug}/daily-report`,supabase=await createClient();const{error}=await supabase.rpc("save_daily_report_note",{target_station:val(form,"stationId",36),target_date:val(form,"date",10),note_content:val(form,"content",4000)});if(error)fail(base,"Yönetici notu kaydedilemedi.");revalidatePath(base)}
export async function createSourceTaskAction(form:FormData){const slug=val(form,"stationSlug",120),source=val(form,"source",20),base=`/station/${slug}/${source==='issue'?'issues':'checklists'}`,supabase=await createClient();const{data,error}=await supabase.rpc("create_source_task",{source_kind:source,target_source:val(form,"sourceId",36),task_title:val(form,"title",160)});if(error||!data)fail(base,"Bu kayıt için görev oluşturulamadı veya görev zaten mevcut.");redirect(`/station/${slug}/tasks/${data}`)}
