"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, LoaderCircle } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { hasSupabaseEnv } from "@/lib/supabase/config";

export function AuthForm({mode}:{mode:"login"|"register"}){const router=useRouter();const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");if(!hasSupabaseEnv()){setMessage("Demo modu: Supabase bilgileri eklendiğinde giriş aktif olacak.");setBusy(false);return}const form=new FormData(e.currentTarget);const email=String(form.get("email"));const password=String(form.get("password"));const supabase=createClient();const result=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{first_name:String(form.get("firstName")),last_name:String(form.get("lastName"))}}});if(result.error){setMessage(result.error.message);setBusy(false);return}router.push(mode==="login"?"/dashboard":"/pending");router.refresh()}
return <form onSubmit={submit} className="mt-8 space-y-4">{mode==="register"&&<div className="grid grid-cols-2 gap-3"><label className="space-y-2 text-sm">Ad<input name="firstName" className="input" required autoComplete="given-name"/></label><label className="space-y-2 text-sm">Soyad<input name="lastName" className="input" required autoComplete="family-name"/></label></div>}<label className="block space-y-2 text-sm">E-posta<input name="email" type="email" className="input" required autoComplete="email" placeholder="ad.soyad@aytemiz.com.tr"/></label><label className="block space-y-2 text-sm">Şifre<input name="password" type="password" minLength={8} className="input" required autoComplete={mode==="login"?"current-password":"new-password"}/></label>{message&&<p role="alert" className="rounded-xl border border-amber-900/50 bg-amber-950/30 p-3 text-sm text-amber-200">{message}</p>}<button className="btn-primary w-full" disabled={busy}>{busy?<LoaderCircle className="animate-spin" size={18}/>:<>{mode==="login"?"Giriş yap":"Hesap oluştur"}<ArrowRight size={18}/></>}</button><p className="muted text-center text-sm">{mode==="login"?"Hesabınız yok mu?":"Zaten hesabınız var mı?"} <Link className="font-semibold text-rose-400" href={mode==="login"?"/register":"/login"}>{mode==="login"?"Kayıt olun":"Giriş yapın"}</Link></p></form>}
