-- Operations, announcements, notification center and ambiguity-safe user directory.
create table public.operation_posts(
 id uuid primary key default gen_random_uuid(),station_id uuid not null references public.stations(id),created_by uuid not null references public.profiles(id),title text not null check(char_length(title) between 3 and 160),description text check(description is null or char_length(description)<=4000),shift_id uuid references public.shifts(id),status text not null default 'draft' check(status in('draft','published')),published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),edited_at timestamptz,deleted_at timestamptz,deleted_by uuid references auth.users(id),version integer not null default 1 check(version>0),check((status='draft' and published_at is null) or (status='published' and published_at is not null))
);
create table public.operation_post_participants(post_id uuid not null references public.operation_posts(id) on delete cascade,user_id uuid not null references public.profiles(id),primary key(post_id,user_id));
create table public.operation_post_media(post_id uuid not null references public.operation_posts(id) on delete cascade,media_id uuid not null references public.media_assets(id),sort_order integer not null default 0,primary key(post_id,media_id));
do $$declare n text;begin foreach n in array array['operation_posts','operation_post_participants','operation_post_media'] loop execute format('alter table public.%I enable row level security',n);execute format('revoke all on public.%I from anon,authenticated',n);execute format('grant select on public.%I to authenticated',n);end loop;end$$;
create index operation_posts_station_cursor_idx on public.operation_posts(station_id,created_at desc,id desc) where deleted_at is null;
create index operation_posts_filter_idx on public.operation_posts(station_id,status,shift_id,published_at desc) where deleted_at is null;
create index operation_participants_user_idx on public.operation_post_participants(user_id,post_id);

insert into public.permissions(name,slug,category,scope_type,is_system_permission) values
('Durum Gönderisini Süre Sonrası Düzenle','status_posts.override_edit','Durum Gönderileri','station',true)
on conflict(slug) do update set name=excluded.name,category=excluded.category,scope_type=excluded.scope_type,is_system_permission=true;
with rs(slug) as(values('regional_manager'),('station_manager'),('assistant_station_manager')) insert into public.role_permissions(role_id,permission_id,scope_kind,granted) select r.id,p.id,'assigned',true from rs join public.roles r using(slug) cross join public.permissions p where p.slug='status_posts.override_edit' on conflict do nothing;

create or replace function private.can_view_operation_post(target_post uuid,check_user uuid default auth.uid()) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.operation_posts p where p.id=target_post and p.deleted_at is null and ((p.status='draft' and p.created_by=check_user) or (p.status='published' and private.has_permission_in_scope('status_posts.view',p.station_id,null,check_user))))$$;
revoke all on function private.can_view_operation_post(uuid,uuid) from public,anon;grant execute on function private.can_view_operation_post(uuid,uuid) to authenticated;
create policy operation_posts_read on public.operation_posts for select to authenticated using(private.can_view_operation_post(id));
create policy operation_participants_read on public.operation_post_participants for select to authenticated using(private.can_view_operation_post(post_id));
create policy operation_media_read on public.operation_post_media for select to authenticated using(private.can_view_operation_post(post_id));

alter table public.announcements add column if not exists region_id uuid references public.regions(id);
alter table public.announcements add column if not exists severity text not null default 'normal';
alter table public.announcements add column if not exists scope_kind text not null default 'station';
alter table public.announcements add column if not exists status text not null default 'published';
alter table public.announcements add column if not exists published_at timestamptz;
alter table public.announcements add column if not exists updated_at timestamptz not null default now();
alter table public.announcements add column if not exists deleted_at timestamptz;
alter table public.announcements add column if not exists deleted_by uuid references auth.users(id);
alter table public.announcements add column if not exists version integer not null default 1;
update public.announcements set scope_kind=case when station_id is null then 'global' else 'station' end;
update public.announcements set published_at=created_at where status='published' and published_at is null;
alter table public.announcements add constraint announcements_severity_check check(severity in('normal','important','urgent'));
alter table public.announcements add constraint announcements_scope_check check((scope_kind='global' and station_id is null and region_id is null) or(scope_kind='region' and region_id is not null and station_id is null)or(scope_kind='station' and station_id is not null and region_id is null));
alter table public.announcements add constraint announcements_status_check check(status in('draft','published','archived'));
create table public.announcement_reads(announcement_id uuid not null references public.announcements(id) on delete cascade,user_id uuid not null references public.profiles(id),read_at timestamptz not null default now(),primary key(announcement_id,user_id));
create table public.announcement_media(announcement_id uuid not null references public.announcements(id) on delete cascade,media_id uuid not null references public.media_assets(id),kind text not null default 'attachment' check(kind in('cover','attachment')),sort_order integer not null default 0,primary key(announcement_id,media_id));
alter table public.announcement_reads enable row level security;alter table public.announcement_media enable row level security;
revoke all on public.announcement_reads,public.announcement_media from anon,authenticated;grant select on public.announcement_reads,public.announcement_media to authenticated;
create index announcements_scope_cursor_idx on public.announcements(scope_kind,station_id,region_id,published_at desc,id desc) where deleted_at is null;
create index announcement_reads_user_idx on public.announcement_reads(user_id,read_at desc);

alter table public.notifications add column if not exists read_at timestamptz;
update public.notifications set read_at=created_at where is_read and read_at is null;
create index notifications_user_cursor_idx on public.notifications(user_id,created_at desc,id desc);
create index notifications_unread_idx on public.notifications(user_id,created_at desc) where read_at is null;

-- Keep every mutation behind a permission-aware private implementation. Public
-- wrappers are SECURITY INVOKER so PostgREST never exposes a definer function.
create function private.create_operation_post(target_station uuid,post_title text,post_description text,target_shift uuid,participant_ids uuid[],asset_ids uuid[],save_as_draft boolean)
returns uuid language plpgsql security definer set search_path='' as $$
declare new_id uuid;begin
 if not private.has_permission_in_scope('status_posts.create',target_station) then raise exception 'Operasyon kaydı oluşturma yetkiniz yok';end if;
 if char_length(trim(post_title)) not between 3 and 160 or char_length(coalesce(post_description,''))>4000 then raise exception 'Gönderi alanlarını kontrol edin';end if;
 if not save_as_draft and cardinality(coalesce(asset_ids,'{}'))=0 then raise exception 'En az bir fotoğraf ekleyin';end if;
 if exists(select 1 from unnest(coalesce(participant_ids,'{}')) u where not exists(select 1 from public.user_station_assignments a join public.profiles p on p.id=a.user_id where a.station_id=target_station and a.user_id=u and p.status='active' and p.deleted_at is null)) then raise exception 'Seçilen personel istasyonda aktif değil';end if;
 if exists(select 1 from unnest(coalesce(asset_ids,'{}')) a where not exists(select 1 from public.media_assets m where m.id=a and m.station_id=target_station and m.owner_id=(select auth.uid()) and m.bucket='operation-media' and m.deleted_at is null)) then raise exception 'Geçersiz medya kaydı';end if;
 insert into public.operation_posts(station_id,created_by,title,description,shift_id,status,published_at) values(target_station,(select auth.uid()),trim(post_title),nullif(trim(post_description),''),target_shift,case when save_as_draft then 'draft' else 'published' end,case when save_as_draft then null else now() end) returning id into new_id;
 insert into public.operation_post_participants(post_id,user_id) select new_id,u from unnest(coalesce(participant_ids,'{}')) u;
 insert into public.operation_post_media(post_id,media_id,sort_order) select new_id,a,row_number() over() from unnest(coalesce(asset_ids,'{}')) a;
 if not save_as_draft then insert into public.notifications(user_id,title,body,type,entity_type,entity_id,station_id,action_url,severity,deduplication_key)
 select a.user_id,'Yeni operasyon kaydı',trim(post_title),'operation_post','operation_post',new_id,target_station,'/station/'||s.slug||'/photos/'||new_id,'normal','operation:'||new_id||':'||a.user_id from public.user_station_assignments a join public.stations s on s.id=a.station_id where a.station_id=target_station and a.user_id<>(select auth.uid()) and private.has_permission_in_scope('status_posts.view',target_station,null,a.user_id) on conflict(user_id,deduplication_key) where deduplication_key is not null do nothing;end if;
 return new_id;end$$;

create function private.update_operation_post(target_post uuid,post_title text,post_description text,target_shift uuid,participant_ids uuid[],publish_now boolean)
returns void language plpgsql security definer set search_path='' as $$declare p public.operation_posts;override_used boolean;begin
 select * into p from public.operation_posts where id=target_post and deleted_at is null for update;if p.id is null then raise exception 'Gönderi bulunamadı';end if;
 override_used:=private.has_permission_in_scope('status_posts.override_edit',p.station_id);
 if not ((p.created_by=(select auth.uid()) and now()<=p.created_at+interval '60 minutes' and private.has_permission_in_scope('status_posts.edit_own',p.station_id)) or private.has_permission_in_scope('status_posts.edit_any',p.station_id) or override_used) then raise exception 'Düzenleme süresi doldu veya yetkiniz yok';end if;
 if char_length(trim(post_title)) not between 3 and 160 then raise exception 'Başlığı kontrol edin';end if;
 if exists(select 1 from unnest(coalesce(participant_ids,'{}')) u where not exists(select 1 from public.user_station_assignments a join public.profiles pr on pr.id=a.user_id where a.station_id=p.station_id and a.user_id=u and pr.status='active' and pr.deleted_at is null)) then raise exception 'Seçilen personel istasyonda aktif değil';end if;
 update public.operation_posts set title=trim(post_title),description=nullif(trim(post_description),''),shift_id=target_shift,status=case when publish_now then 'published' else status end,published_at=case when publish_now then coalesce(published_at,now()) else published_at end,updated_at=now(),edited_at=now(),version=version+1 where id=target_post;
 delete from public.operation_post_participants where post_id=target_post;insert into public.operation_post_participants select target_post,u from unnest(coalesce(participant_ids,'{}')) u;
 if override_used and not (p.created_by=(select auth.uid()) and now()<=p.created_at+interval '60 minutes') then insert into public.audit_logs(actor_user_id,action,target_type,target_id,station_id,metadata) values((select auth.uid()),'override_edit','operation_posts',target_post::text,p.station_id,jsonb_build_object('reason','60_minute_override'));end if;
end$$;

create function private.delete_operation_post(target_post uuid) returns void language plpgsql security definer set search_path='' as $$declare p public.operation_posts;begin select * into p from public.operation_posts where id=target_post and deleted_at is null for update;if p.id is null then raise exception 'Gönderi bulunamadı';end if;if not private.has_permission_in_scope('status_posts.delete',p.station_id) then raise exception 'Silme yetkiniz yok';end if;update public.operation_posts set deleted_at=now(),deleted_by=(select auth.uid()),updated_at=now(),version=version+1 where id=target_post;insert into public.audit_logs(actor_user_id,action,target_type,target_id,station_id,metadata) values((select auth.uid()),'soft_delete','operation_posts',target_post::text,p.station_id,'{}');end$$;

create function private.list_operation_posts(target_station uuid,status_filter text default 'published',search_text text default null,date_from date default null,date_to date default null,target_shift uuid default null,target_person uuid default null,cursor_created timestamptz default null,cursor_id uuid default null,page_size integer default 12)
returns table(id uuid,title text,description text,status text,created_at timestamptz,created_by uuid,creator_name text,creator_roles text[],station_id uuid,station_name text,station_slug text,shift_name text,participants jsonb,media jsonb,can_edit boolean) language sql stable security definer set search_path='' as $$
select p.id,p.title,p.description,p.status,p.created_at,p.created_by,trim(c.first_name||' '||c.last_name),coalesce((select array_agg(distinct r.name order by r.name) from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=p.created_by),'{}'),p.station_id,s.name,s.slug,sh.name,
coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'name',trim(x.first_name||' '||x.last_name)) order by x.first_name,x.last_name) from public.operation_post_participants pp join public.profiles x on x.id=pp.user_id where pp.post_id=p.id),'[]'),
coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'bucket',m.bucket,'path',m.storage_path,'name',m.original_name,'mime',m.mime_type) order by pm.sort_order) from public.operation_post_media pm join public.media_assets m on m.id=pm.media_id where pm.post_id=p.id and m.deleted_at is null),'[]'),
((p.created_by=(select auth.uid()) and now()<=p.created_at+interval '60 minutes' and private.has_permission_in_scope('status_posts.edit_own',p.station_id)) or private.has_permission_in_scope('status_posts.edit_any',p.station_id) or private.has_permission_in_scope('status_posts.override_edit',p.station_id))
from public.operation_posts p join public.profiles c on c.id=p.created_by join public.stations s on s.id=p.station_id left join public.shifts sh on sh.id=p.shift_id where p.station_id=target_station and private.can_view_operation_post(p.id) and (status_filter is null or status_filter='' or p.status=status_filter) and (search_text is null or search_text='' or p.title ilike '%'||search_text||'%' or coalesce(p.description,'') ilike '%'||search_text||'%' or trim(c.first_name||' '||c.last_name) ilike '%'||search_text||'%') and (date_from is null or p.created_at>=(date_from::timestamp at time zone 'Europe/Istanbul')) and (date_to is null or p.created_at<((date_to+1)::timestamp at time zone 'Europe/Istanbul')) and (target_shift is null or p.shift_id=target_shift) and (target_person is null or p.created_by=target_person or exists(select 1 from public.operation_post_participants pp where pp.post_id=p.id and pp.user_id=target_person)) and (cursor_created is null or (p.created_at,p.id)<(cursor_created,coalesce(cursor_id,'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid))) order by p.created_at desc,p.id desc limit least(greatest(page_size,1),50)$$;

create function private.get_operation_post(target_post uuid) returns jsonb language sql stable security definer set search_path='' as $$select to_jsonb(x)||jsonb_build_object('can_delete',private.has_permission_in_scope('status_posts.delete',x.station_id)) from private.list_operation_posts((select station_id from public.operation_posts where id=target_post),null,null,null,null,null,null,null,null,50) x where x.id=target_post$$;

create function public.create_operation_post(target_station uuid,post_title text,post_description text,target_shift uuid,participant_ids uuid[],asset_ids uuid[],save_as_draft boolean default false) returns uuid language sql volatile security invoker set search_path='' as $$select private.create_operation_post(target_station,post_title,post_description,target_shift,participant_ids,asset_ids,save_as_draft)$$;
create function public.update_operation_post(target_post uuid,post_title text,post_description text,target_shift uuid,participant_ids uuid[],publish_now boolean default false) returns void language sql volatile security invoker set search_path='' as $$select private.update_operation_post(target_post,post_title,post_description,target_shift,participant_ids,publish_now)$$;
create function public.delete_operation_post(target_post uuid) returns void language sql volatile security invoker set search_path='' as $$select private.delete_operation_post(target_post)$$;
create function public.list_operation_posts(target_station uuid,status_filter text default 'published',search_text text default null,date_from date default null,date_to date default null,target_shift uuid default null,target_person uuid default null,cursor_created timestamptz default null,cursor_id uuid default null,page_size integer default 12) returns table(id uuid,title text,description text,status text,created_at timestamptz,created_by uuid,creator_name text,creator_roles text[],station_id uuid,station_name text,station_slug text,shift_name text,participants jsonb,media jsonb,can_edit boolean) language sql stable security invoker set search_path='' as $$select * from private.list_operation_posts(target_station,status_filter,search_text,date_from,date_to,target_shift,target_person,cursor_created,cursor_id,page_size)$$;
create function public.get_operation_post(target_post uuid) returns jsonb language sql stable security invoker set search_path='' as $$select private.get_operation_post(target_post)$$;

-- Announcement scope and receipts.
create function private.can_view_announcement(target_announcement uuid,check_user uuid default auth.uid()) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.announcements a where a.id=target_announcement and a.deleted_at is null and ((a.status='draft' and a.created_by=check_user) or (a.status='published' and private.has_permission_in_scope('announcements.view',a.station_id,a.region_id,check_user) and (a.scope_kind='global' or (a.scope_kind='station' and (private.is_op(check_user) or exists(select 1 from public.user_station_assignments x where x.user_id=check_user and x.station_id=a.station_id))) or (a.scope_kind='region' and (private.is_op(check_user) or exists(select 1 from public.user_region_assignments x where x.user_id=check_user and x.region_id=a.region_id) or exists(select 1 from public.user_station_assignments x join public.stations s on s.id=x.station_id where x.user_id=check_user and s.region_id=a.region_id)))))))$$;
drop policy if exists station_announcements on public.announcements;create policy announcements_scoped_read on public.announcements for select to authenticated using(private.can_view_announcement(id));
create policy announcement_reads_self on public.announcement_reads for select to authenticated using(user_id=(select auth.uid()) or private.has_permission_in_scope('announcements.edit_any',(select station_id from public.announcements where id=announcement_id),(select region_id from public.announcements where id=announcement_id)));
create policy announcement_media_read on public.announcement_media for select to authenticated using(private.can_view_announcement(announcement_id));

create function private.announcement_recipients(a public.announcements) returns setof uuid language sql stable security definer set search_path='' as $$select p.id from public.profiles p where p.status='active' and p.deleted_at is null and private.can_view_announcement(a.id,p.id)$$;
create function private.notify_announcement(target_announcement uuid,event_name text) returns void language plpgsql security definer set search_path='' as $$declare a public.announcements;s text;begin select * into a from public.announcements where id=target_announcement;select slug into s from public.stations where id=a.station_id;insert into public.notifications(user_id,title,body,type,entity_type,entity_id,station_id,action_url,severity,deduplication_key) select u,case when event_name='announcement_updated' then 'Duyuru güncellendi' else case a.severity when 'urgent' then 'Acil duyuru' else 'Yeni önemli duyuru' end end,a.title,event_name,'announcement',a.id,a.station_id,case when s is null then '/notifications' else '/station/'||s||'/announcements/'||a.id end,a.severity,event_name||':'||a.id||':'||a.version||':'||u from private.announcement_recipients(a) u where u<>a.created_by on conflict(user_id,deduplication_key) where deduplication_key is not null do nothing;end$$;
create function private.create_announcement(announcement_title text,announcement_body text,importance text,target_scope text,target_station uuid,target_region uuid,asset_ids uuid[],save_as_draft boolean) returns uuid language plpgsql security definer set search_path='' as $$declare aid uuid;begin if not private.has_permission_in_scope('announcements.create',target_station,target_region) then raise exception 'Duyuru oluşturma yetkiniz yok';end if;if importance not in('normal','important','urgent') or target_scope not in('global','region','station') then raise exception 'Geçersiz duyuru seçeneği';end if;if (target_scope='global' and (target_station is not null or target_region is not null)) or (target_scope='region' and (target_region is null or target_station is not null)) or (target_scope='station' and (target_station is null or target_region is not null)) then raise exception 'Kapsamı kontrol edin';end if;if exists(select 1 from unnest(coalesce(asset_ids,'{}')) x where not exists(select 1 from public.media_assets m where m.id=x and m.owner_id=(select auth.uid()) and m.bucket='shared-content' and m.deleted_at is null and m.metadata->>'announcement_scope'=target_scope and (target_scope='global' or (target_scope='station' and m.station_id=target_station) or (target_scope='region' and m.metadata->>'region_id'=target_region::text)))) then raise exception 'Geçersiz duyuru medyası';end if;insert into public.announcements(station_id,region_id,title,body,created_by,severity,scope_kind,status,published_at) values(target_station,target_region,trim(announcement_title),trim(announcement_body),(select auth.uid()),importance,target_scope,case when save_as_draft then 'draft' else 'published' end,case when save_as_draft then null else now() end) returning id into aid;insert into public.announcement_media(announcement_id,media_id,kind,sort_order) select aid,x,case when row_number() over()=1 then 'cover' else 'attachment' end,row_number() over() from unnest(coalesce(asset_ids,'{}')) x;if not save_as_draft and importance in('important','urgent') then perform private.notify_announcement(aid,'announcement_created');end if;return aid;end$$;
create function private.mark_announcement_read(target_announcement uuid) returns void language plpgsql security definer set search_path='' as $$begin if not private.can_view_announcement(target_announcement) then raise exception 'Duyuru bulunamadı';end if;insert into public.announcement_reads(announcement_id,user_id) values(target_announcement,(select auth.uid())) on conflict(announcement_id,user_id) do update set read_at=excluded.read_at;end$$;
create function private.update_announcement(target_announcement uuid,announcement_title text,announcement_body text,importance text) returns void language plpgsql security definer set search_path='' as $$declare a public.announcements;begin select * into a from public.announcements where id=target_announcement and deleted_at is null for update;if a.id is null then raise exception 'Duyuru bulunamadı';end if;if not ((a.created_by=(select auth.uid()) and private.has_permission_in_scope('announcements.edit_own',a.station_id,a.region_id)) or private.has_permission_in_scope('announcements.edit_any',a.station_id,a.region_id)) then raise exception 'Duyuru düzenleme yetkiniz yok';end if;if importance not in('normal','important','urgent') then raise exception 'Önem seviyesini kontrol edin';end if;update public.announcements set title=trim(announcement_title),body=trim(announcement_body),severity=importance,updated_at=now(),version=version+1 where id=target_announcement;perform private.notify_announcement(target_announcement,'announcement_updated');end$$;
create function private.delete_announcement(target_announcement uuid) returns void language plpgsql security definer set search_path='' as $$declare a public.announcements;begin select * into a from public.announcements where id=target_announcement and deleted_at is null for update;if a.id is null then raise exception 'Duyuru bulunamadı';end if;if not private.has_permission_in_scope('announcements.delete',a.station_id,a.region_id) then raise exception 'Duyuru silme yetkiniz yok';end if;update public.announcements set deleted_at=now(),deleted_by=(select auth.uid()),updated_at=now(),version=version+1 where id=target_announcement;end$$;
create function public.list_announcements(target_station uuid default null,search_text text default null,severity_filter text default null,unread_only boolean default false,cursor_published timestamptz default null,cursor_id uuid default null,page_size integer default 20) returns table(id uuid,title text,body text,severity text,scope_kind text,station_id uuid,station_name text,region_id uuid,region_name text,status text,published_at timestamptz,created_at timestamptz,creator_name text,creator_roles text[],is_read boolean,read_count bigint,recipient_count bigint,media jsonb) language sql stable security invoker set search_path='' as $$select a.id,a.title,a.body,a.severity,a.scope_kind,a.station_id,s.name,a.region_id,r.name,a.status,a.published_at,a.created_at,trim(p.first_name||' '||p.last_name),coalesce((select array_agg(distinct ro.name order by ro.name) from public.user_roles ur join public.roles ro on ro.id=ur.role_id where ur.user_id=a.created_by),'{}'),exists(select 1 from public.announcement_reads ar where ar.announcement_id=a.id and ar.user_id=(select auth.uid())),(select count(*) from public.announcement_reads ar where ar.announcement_id=a.id),(select count(*) from private.announcement_recipients(a)),coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'bucket',m.bucket,'path',m.storage_path,'name',m.original_name,'mime',m.mime_type,'kind',am.kind) order by am.sort_order) from public.announcement_media am join public.media_assets m on m.id=am.media_id where am.announcement_id=a.id and m.deleted_at is null),'[]') from public.announcements a join public.profiles p on p.id=a.created_by left join public.stations s on s.id=a.station_id left join public.regions r on r.id=a.region_id where private.can_view_announcement(a.id) and (target_station is null or a.station_id=target_station or a.scope_kind in('global','region')) and (search_text is null or search_text='' or a.title ilike '%'||search_text||'%' or a.body ilike '%'||search_text||'%') and (severity_filter is null or severity_filter='' or a.severity=severity_filter) and (not unread_only or not exists(select 1 from public.announcement_reads ar where ar.announcement_id=a.id and ar.user_id=(select auth.uid()))) and (cursor_published is null or (coalesce(a.published_at,a.created_at),a.id)<(cursor_published,coalesce(cursor_id,'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid))) order by coalesce(a.published_at,a.created_at) desc,a.id desc limit least(greatest(page_size,1),50)$$;
create function public.get_announcement_detail(target_announcement uuid) returns jsonb language plpgsql volatile security invoker set search_path='' as $$declare result jsonb;begin perform private.mark_announcement_read(target_announcement);select to_jsonb(x) into result from public.list_announcements(null,null,null,false,null,null,50) x where x.id=target_announcement;return result;end$$;
create function public.create_announcement(announcement_title text,announcement_body text,importance text,target_scope text,target_station uuid,target_region uuid,asset_ids uuid[],save_as_draft boolean default false) returns uuid language sql volatile security invoker set search_path='' as $$select private.create_announcement(announcement_title,announcement_body,importance,target_scope,target_station,target_region,asset_ids,save_as_draft)$$;
create function public.mark_announcement_read(target_announcement uuid) returns void language sql volatile security invoker set search_path='' as $$select private.mark_announcement_read(target_announcement)$$;
create function public.update_announcement(target_announcement uuid,announcement_title text,announcement_body text,importance text) returns void language sql volatile security invoker set search_path='' as $$select private.update_announcement(target_announcement,announcement_title,announcement_body,importance)$$;
create function public.delete_announcement(target_announcement uuid) returns void language sql volatile security invoker set search_path='' as $$select private.delete_announcement(target_announcement)$$;

-- Notification center.
create function private.mark_notification_read(target_notification uuid) returns void language plpgsql security definer set search_path='' as $$begin update public.notifications set is_read=true,read_at=coalesce(read_at,now()) where id=target_notification and user_id=(select auth.uid());if not found then raise exception 'Bildirim bulunamadı';end if;end$$;
create function private.mark_all_notifications_read() returns integer language plpgsql security definer set search_path='' as $$declare n integer;begin update public.notifications set is_read=true,read_at=coalesce(read_at,now()) where user_id=(select auth.uid()) and read_at is null;get diagnostics n=row_count;return n;end$$;
create function public.mark_notification_read(target_notification uuid) returns void language sql volatile security invoker set search_path='' as $$select private.mark_notification_read(target_notification)$$;
create function public.mark_all_notifications_read() returns integer language sql volatile security invoker set search_path='' as $$select private.mark_all_notifications_read()$$;
create function public.notification_unread_count() returns bigint language sql stable security invoker set search_path='' as $$select count(*) from public.notifications where user_id=(select auth.uid()) and read_at is null$$;
create function public.list_notifications(kind_filter text default null,unread_only boolean default false,cursor_created timestamptz default null,cursor_id uuid default null,page_size integer default 30) returns table(id uuid,title text,body text,is_read boolean,read_at timestamptz,type text,entity_type text,entity_id uuid,action_url text,severity text,created_at timestamptz) language sql stable security invoker set search_path='' as $$select n.id,n.title,n.body,n.read_at is not null,n.read_at,n.type,n.entity_type,n.entity_id,n.action_url,n.severity,n.created_at from public.notifications n where n.user_id=(select auth.uid()) and (not unread_only or n.read_at is null) and (kind_filter is null or kind_filter='' or kind_filter='all' or n.entity_type=kind_filter or (kind_filter='system' and n.entity_type is null)) and (cursor_created is null or (n.created_at,n.id)<(cursor_created,coalesce(cursor_id,'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid))) order by n.created_at desc,n.id desc limit least(greatest(page_size,1),50)$$;

-- One optimized, ambiguity-safe directory call for pickers.
create function public.search_user_directory(search_text text default null,target_station uuid default null,cursor_name text default null,cursor_id uuid default null,page_size integer default 30)
returns table(user_id uuid,display_name text,email text,status public.profile_status,roles text[],stations jsonb,regions text[]) language sql stable security invoker set search_path='' as $$
select p.id,coalesce(nullif(trim(p.first_name||' '||p.last_name),''),'İsimsiz kullanıcı'),case when p.id=(select auth.uid()) or private.has_permission_in_scope('personnel.view_directory',target_station) or private.has_permission_in_scope('roles.assign_permissions') then p.email else null end,p.status,
coalesce((select array_agg(distinct r.name order by r.name) from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=p.id),'{}'),coalesce((select jsonb_agg(distinct jsonb_build_object('id',s.id,'name',s.name,'city',s.city)) from public.user_station_assignments a join public.stations s on s.id=a.station_id where a.user_id=p.id),'[]'),coalesce((select array_agg(distinct r.name order by r.name) from public.user_region_assignments a join public.regions r on r.id=a.region_id where a.user_id=p.id),'{}')
from public.profiles p where p.deleted_at is null and (target_station is null or exists(select 1 from public.user_station_assignments a where a.user_id=p.id and a.station_id=target_station)) and (private.has_permission_in_scope('personnel.view_directory',target_station) or private.has_permission_in_scope('roles.assign_permissions') or p.id=(select auth.uid())) and (search_text is null or search_text='' or trim(p.first_name||' '||p.last_name) ilike '%'||search_text||'%' or (private.has_permission_in_scope('roles.assign_permissions') and p.email ilike '%'||search_text||'%')) and (cursor_name is null or (lower(trim(p.first_name||' '||p.last_name)),p.id)>(lower(cursor_name),coalesce(cursor_id,'00000000-0000-0000-0000-000000000000'::uuid))) order by lower(trim(p.first_name||' '||p.last_name)),p.id limit least(greatest(page_size,1),50)$$;

create function private.remove_user_permission(target_exception uuid) returns void language plpgsql security definer set search_path='' as $$begin if not private.has_permission_in_scope('roles.assign_permissions') then raise exception 'Yetki istisnası kaldırma izniniz yok';end if;delete from public.user_permissions where id=target_exception;if not found then raise exception 'İstisna bulunamadı';end if;end$$;
create function public.remove_user_permission(target_exception uuid) returns void language sql volatile security invoker set search_path='' as $$select private.remove_user_permission(target_exception)$$;

-- Explicit function grants are required for new Data API functions.
revoke all on function private.create_operation_post(uuid,text,text,uuid,uuid[],uuid[],boolean),private.update_operation_post(uuid,text,text,uuid,uuid[],boolean),private.delete_operation_post(uuid),private.list_operation_posts(uuid,text,text,date,date,uuid,uuid,timestamptz,uuid,integer),private.get_operation_post(uuid),private.can_view_announcement(uuid,uuid),private.announcement_recipients(public.announcements),private.notify_announcement(uuid,text),private.create_announcement(text,text,text,text,uuid,uuid,uuid[],boolean),private.mark_announcement_read(uuid),private.update_announcement(uuid,text,text,text),private.delete_announcement(uuid),private.mark_notification_read(uuid),private.mark_all_notifications_read(),private.remove_user_permission(uuid) from public,anon,authenticated;
grant execute on function public.create_operation_post(uuid,text,text,uuid,uuid[],uuid[],boolean),public.update_operation_post(uuid,text,text,uuid,uuid[],boolean),public.delete_operation_post(uuid),public.list_operation_posts(uuid,text,text,date,date,uuid,uuid,timestamptz,uuid,integer),public.get_operation_post(uuid),public.create_announcement(text,text,text,text,uuid,uuid,uuid[],boolean),public.mark_announcement_read(uuid),public.update_announcement(uuid,text,text,text),public.delete_announcement(uuid),public.list_announcements(uuid,text,text,boolean,timestamptz,uuid,integer),public.get_announcement_detail(uuid),public.mark_notification_read(uuid),public.mark_all_notifications_read(),public.notification_unread_count(),public.list_notifications(text,boolean,timestamptz,uuid,integer),public.search_user_directory(text,uuid,text,uuid,integer),public.remove_user_permission(uuid) to authenticated;

create policy operation_media_object_insert on storage.objects for insert to authenticated with check(bucket_id='operation-media' and name ~ '^operations/[0-9a-f-]{36}/[0-9a-f-]{36}/[0-9a-f-]{36}\.(jpg|jpeg|png|webp)$' and (storage.foldername(name))[3]=(select auth.uid())::text and private.has_permission_in_scope('status_posts.create',((storage.foldername(name))[2])::uuid));
create policy operation_media_object_select on storage.objects for select to authenticated using(bucket_id='operation-media' and (storage.foldername(name))[1]='operations' and exists(select 1 from public.media_assets m join public.operation_post_media pm on pm.media_id=m.id where m.storage_path=name and private.can_view_operation_post(pm.post_id)));

drop policy if exists media_assets_insert on public.media_assets;
create policy media_assets_insert on public.media_assets for insert to authenticated with check(uploaded_by=(select auth.uid()) and owner_id=(select auth.uid()) and deleted_at is null and ((bucket='profile-media' and station_id is null) or (bucket='operation-media' and station_id is not null and (private.has_permission_in_scope('status_posts.create',station_id,null) or (storage_path like 'tasks/%' and exists(select 1 from public.tasks t join public.task_assignees ta on ta.task_id=t.id where t.id=(split_part(storage_path,'/',3))::uuid and t.station_id=media_assets.station_id and ta.user_id=(select auth.uid()) and t.deleted_at is null)))) or (bucket='shared-content' and ((metadata->>'announcement_scope'='global' and station_id is null and private.has_permission_in_scope('announcements.create')) or (metadata->>'announcement_scope'='region' and station_id is null and private.has_permission_in_scope('announcements.create',null,(metadata->>'region_id')::uuid)) or (metadata->>'announcement_scope'='station' and station_id is not null and private.has_permission_in_scope('announcements.create',station_id,null)) or (metadata->>'announcement_scope' is null and (station_id is null or private.has_permission_in_scope('files.upload',station_id,null))))) or (bucket='brand-assets' and private.has_permission_in_scope('system.manage_settings'))));
create policy announcement_content_insert on storage.objects for insert to authenticated with check(bucket_id='shared-content' and name ~ '^announcements/(global|region|station)/([0-9a-f-]{36}|global)/[0-9a-f-]{36}/[0-9a-f-]{36}\.(jpg|jpeg|png|webp|pdf|txt)$' and (storage.foldername(name))[4]=(select auth.uid())::text and (((storage.foldername(name))[2]='global' and private.has_permission_in_scope('announcements.create')) or ((storage.foldername(name))[2]='station' and private.has_permission_in_scope('announcements.create',((storage.foldername(name))[3])::uuid,null)) or ((storage.foldername(name))[2]='region' and private.has_permission_in_scope('announcements.create',null,((storage.foldername(name))[3])::uuid))));
create policy announcement_content_select on storage.objects for select to authenticated using(bucket_id='shared-content' and (storage.foldername(name))[1]='announcements' and exists(select 1 from public.media_assets m join public.announcement_media am on am.media_id=m.id where m.storage_path=name and private.can_view_announcement(am.announcement_id)));

create trigger audit_operation_posts after insert or update or delete on public.operation_posts for each row execute function private.audit_change();
create trigger audit_announcements after insert or update or delete on public.announcements for each row execute function private.audit_change();
