-- Phase 6: station operations, handovers, checklists, issues and daily reporting.
create table public.shift_handovers(id uuid primary key default gen_random_uuid(),station_id uuid not null references public.stations(id),shift_id uuid not null references public.shifts(id),handover_date date not null,created_by uuid not null references public.profiles(id),status text not null default 'draft' check(status in('draft','submitted','acknowledged','closed')),general_note text,next_shift_note text,created_at timestamptz not null default now(),submitted_at timestamptz,updated_at timestamptz not null default now(),deleted_at timestamptz,version integer not null default 1);
create unique index shift_handovers_active_unique on public.shift_handovers(station_id,shift_id,handover_date) where deleted_at is null;
create index shift_handovers_station_cursor on public.shift_handovers(station_id,handover_date desc,created_at desc,id desc) where deleted_at is null;
create table public.shift_handover_items(id uuid primary key default gen_random_uuid(),handover_id uuid not null references public.shift_handovers(id) on delete cascade,section_key text not null,condition text not null check(condition in('ok','attention','issue')),note text,sort_order integer not null default 0,unique(handover_id,section_key));
create table public.shift_handover_participants(handover_id uuid not null references public.shift_handovers(id) on delete cascade,user_id uuid not null references public.profiles(id),participant_type text not null check(participant_type in('outgoing','incoming','mentioned')),primary key(handover_id,user_id,participant_type));
create table public.shift_handover_acknowledgements(handover_id uuid not null references public.shift_handovers(id) on delete cascade,user_id uuid not null references public.profiles(id),acknowledged_at timestamptz not null default now(),primary key(handover_id,user_id));
create table public.shift_handover_events(id bigint generated always as identity primary key,handover_id uuid not null references public.shift_handovers(id) on delete cascade,actor_id uuid references public.profiles(id),event_type text not null,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.shift_handover_media(handover_id uuid not null references public.shift_handovers(id) on delete cascade,media_asset_id uuid not null references public.media_assets(id),primary key(handover_id,media_asset_id));

create table public.checklist_templates(id uuid primary key default gen_random_uuid(),station_id uuid references public.stations(id),region_id uuid references public.regions(id),name text not null,description text,scope_type text not null check(scope_type in('station','region','global')),shift_id uuid references public.shifts(id),is_active boolean not null default true,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,constraint checklist_template_scope check((scope_type='global' and station_id is null and region_id is null) or (scope_type='region' and region_id is not null and station_id is null) or (scope_type='station' and station_id is not null and region_id is null)));
create index checklist_templates_scope_idx on public.checklist_templates(scope_type,station_id,region_id,shift_id) where deleted_at is null and is_active;
create table public.checklist_template_items(id uuid primary key default gen_random_uuid(),template_id uuid not null references public.checklist_templates(id) on delete cascade,title text not null,description text,sort_order integer not null default 0,is_required boolean not null default true,requires_note boolean not null default false,requires_photo boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.checklist_runs(id uuid primary key default gen_random_uuid(),template_id uuid not null references public.checklist_templates(id),station_id uuid not null references public.stations(id),shift_id uuid references public.shifts(id),run_date date not null,assigned_to uuid references public.profiles(id),status text not null default 'pending' check(status in('pending','in_progress','completed','overdue','cancelled')),started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(template_id,station_id,run_date,shift_id));
create index checklist_runs_station_cursor on public.checklist_runs(station_id,run_date desc,status,id desc);
create table public.checklist_run_items(id uuid primary key default gen_random_uuid(),run_id uuid not null references public.checklist_runs(id) on delete cascade,template_item_id uuid not null references public.checklist_template_items(id),status text not null default 'pending' check(status in('pending','completed','skipped','issue')),note text,completed_by uuid references public.profiles(id),completed_at timestamptz,updated_at timestamptz not null default now(),unique(run_id,template_item_id));
create table public.checklist_run_item_media(run_item_id uuid not null references public.checklist_run_items(id) on delete cascade,media_asset_id uuid not null references public.media_assets(id),primary key(run_item_id,media_asset_id));

create table public.station_issues(id uuid primary key default gen_random_uuid(),station_id uuid not null references public.stations(id),created_by uuid not null references public.profiles(id),title text not null,description text not null,category text not null,priority text not null default 'normal' check(priority in('low','normal','high','critical')),status text not null default 'open' check(status in('open','investigating','waiting_service','resolved','closed','cancelled')),asset_name text,asset_code text,assigned_to uuid references public.profiles(id),opened_at timestamptz not null default now(),resolved_at timestamptz,closed_at timestamptz,updated_at timestamptz not null default now(),deleted_at timestamptz,version integer not null default 1);
create index station_issues_cursor_idx on public.station_issues(station_id,opened_at desc,id desc) where deleted_at is null;
create index station_issues_status_priority_idx on public.station_issues(station_id,status,priority) where deleted_at is null;
create table public.station_issue_events(id bigint generated always as identity primary key,issue_id uuid not null references public.station_issues(id) on delete cascade,actor_id uuid references public.profiles(id),event_type text not null,body text,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.station_issue_media(issue_id uuid not null references public.station_issues(id) on delete cascade,media_asset_id uuid not null references public.media_assets(id),primary key(issue_id,media_asset_id));
create table public.station_daily_report_notes(id uuid primary key default gen_random_uuid(),station_id uuid not null references public.stations(id),report_date date not null,created_by uuid not null references public.profiles(id),content text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create index station_daily_notes_idx on public.station_daily_report_notes(station_id,report_date,created_at desc) where deleted_at is null;
alter table public.tasks add column if not exists source_type text;
alter table public.tasks add column if not exists source_id uuid;
create unique index tasks_source_unique on public.tasks(source_type,source_id) where source_type is not null and source_id is not null and deleted_at is null;

do $$declare t text;begin foreach t in array array['shift_handovers','shift_handover_items','shift_handover_participants','shift_handover_acknowledgements','shift_handover_events','shift_handover_media','checklist_templates','checklist_template_items','checklist_runs','checklist_run_items','checklist_run_item_media','station_issues','station_issue_events','station_issue_media','station_daily_report_notes'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);end loop;end$$;

insert into public.permissions(name,slug,category,scope_type,is_system_permission) values
('Devir Teslim Görüntüle','handovers.view','Devir Teslim','station',true),('Devir Teslim Oluştur','handovers.create','Devir Teslim','station',true),('Devir Teslim Onayla','handovers.acknowledge','Devir Teslim','station',true),('Devir Teslim Yönet','handovers.override','Devir Teslim','station',true),
('Checklist Görüntüle','checklists.view','Checklist','station',true),('Checklist Şablonu Oluştur','checklists.create_template','Checklist','both',true),('Checklist Şablonu Düzenle','checklists.edit_template','Checklist','both',true),('Checklist Şablonu Sil','checklists.delete_template','Checklist','both',true),('Checklist Uygula','checklists.execute','Checklist','station',true),('Checklist İncele','checklists.review','Checklist','station',true),('Checklist Override','checklists.override','Checklist','station',true),
('Arıza Görüntüle','issues.view','Arıza ve Bakım','station',true),('Arıza Oluştur','issues.create','Arıza ve Bakım','station',true),('Arıza Düzenle','issues.edit','Arıza ve Bakım','station',true),('Arıza Ata','issues.assign','Arıza ve Bakım','station',true),('Arıza Çöz','issues.resolve','Arıza ve Bakım','station',true),('Arıza Kapat','issues.close','Arıza ve Bakım','station',true),('Arıza Sil','issues.delete','Arıza ve Bakım','station',true),('Arıza Override','issues.override','Arıza ve Bakım','station',true),
('Günlük Rapor Görüntüle','daily_reports.view','Günlük Rapor','station',true),('Günlük Rapor Notu','daily_reports.note','Günlük Rapor','station',true),('Günlük Rapor Not Override','daily_reports.override','Günlük Rapor','station',true)
on conflict(slug) do update set name=excluded.name,category=excluded.category,scope_type=excluded.scope_type,is_system_permission=true;
with rs(slug) as(values('regional_manager'),('station_manager'),('assistant_station_manager')),ps(slug) as(values('handovers.view'),('handovers.create'),('handovers.acknowledge'),('handovers.override'),('checklists.view'),('checklists.create_template'),('checklists.edit_template'),('checklists.delete_template'),('checklists.execute'),('checklists.review'),('checklists.override'),('issues.view'),('issues.create'),('issues.edit'),('issues.assign'),('issues.resolve'),('issues.close'),('issues.delete'),('issues.override'),('daily_reports.view'),('daily_reports.note'),('daily_reports.override')) insert into public.role_permissions(role_id,permission_id,scope_kind,granted) select r.id,p.id,'assigned',true from rs join public.roles r on r.slug=rs.slug cross join ps join public.permissions p on p.slug=ps.slug on conflict do nothing;
with rs(slug) as(values('market_team_leader'),('forecourt_team_leader'),('market_sales'),('forecourt_sales'),('cleaning_staff'),('car_wash_staff')),ps(slug) as(values('handovers.view'),('handovers.create'),('handovers.acknowledge'),('checklists.view'),('checklists.execute'),('issues.view'),('issues.create'),('daily_reports.view')) insert into public.role_permissions(role_id,permission_id,scope_kind,granted) select r.id,p.id,'assigned',true from rs join public.roles r on r.slug=rs.slug cross join ps join public.permissions p on p.slug=ps.slug on conflict do nothing;

create function private.can_view_handover(target uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.shift_handovers h where h.id=target and h.deleted_at is null and private.has_permission_in_scope('handovers.view',h.station_id))$$;
create function private.can_view_checklist(target uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.checklist_runs r where r.id=target and private.has_permission_in_scope('checklists.view',r.station_id))$$;
create function private.can_view_issue(target uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.station_issues i where i.id=target and i.deleted_at is null and private.has_permission_in_scope('issues.view',i.station_id))$$;
revoke all on function private.can_view_handover(uuid),private.can_view_checklist(uuid),private.can_view_issue(uuid) from public,anon,authenticated;
grant execute on function private.can_view_handover(uuid),private.can_view_checklist(uuid),private.can_view_issue(uuid) to authenticated;

create policy handovers_read on public.shift_handovers for select to authenticated using(private.can_view_handover(id));
create policy handover_items_read on public.shift_handover_items for select to authenticated using(private.can_view_handover(handover_id));
create policy handover_participants_read on public.shift_handover_participants for select to authenticated using(private.can_view_handover(handover_id));
create policy handover_acks_read on public.shift_handover_acknowledgements for select to authenticated using(private.can_view_handover(handover_id));
create policy handover_events_read on public.shift_handover_events for select to authenticated using(private.can_view_handover(handover_id));
create policy handover_media_read on public.shift_handover_media for select to authenticated using(private.can_view_handover(handover_id));
create policy checklist_templates_read on public.checklist_templates for select to authenticated using(deleted_at is null and (private.is_op() or (scope_type='station' and private.can_access_station(station_id)) or (scope_type='region' and exists(select 1 from public.user_station_assignments a join public.stations s on s.id=a.station_id where a.user_id=(select auth.uid()) and s.region_id=checklist_templates.region_id)) or scope_type='global'));
create policy checklist_template_items_read on public.checklist_template_items for select to authenticated using(exists(select 1 from public.checklist_templates t where t.id=template_id and t.deleted_at is null));
create policy checklist_runs_read on public.checklist_runs for select to authenticated using(private.can_view_checklist(id));
create policy checklist_run_items_read on public.checklist_run_items for select to authenticated using(private.can_view_checklist(run_id));
create policy checklist_run_media_read on public.checklist_run_item_media for select to authenticated using(exists(select 1 from public.checklist_run_items x where x.id=run_item_id and private.can_view_checklist(x.run_id)));
create policy issues_read on public.station_issues for select to authenticated using(private.can_view_issue(id));
create policy issue_events_read on public.station_issue_events for select to authenticated using(private.can_view_issue(issue_id));
create policy issue_media_read on public.station_issue_media for select to authenticated using(private.can_view_issue(issue_id));
create policy daily_notes_read on public.station_daily_report_notes for select to authenticated using(deleted_at is null and private.has_permission_in_scope('daily_reports.view',station_id));

create function private.notify_station(target_station uuid,event_type text,entity_type text,entity_id uuid,title_text text,body_text text,severity_text text,dedup_prefix text) returns void language sql security definer set search_path='' as $$insert into public.notifications(user_id,title,body,type,entity_type,entity_id,station_id,action_url,severity,deduplication_key) select a.user_id,title_text,body_text,event_type,entity_type,entity_id,target_station,'/station/'||s.slug||case entity_type when 'handover' then '/handover' when 'checklist' then '/checklists' else '/issues' end,severity_text,dedup_prefix||':'||a.user_id from public.user_station_assignments a join public.stations s on s.id=a.station_id where a.station_id=target_station and a.user_id<>(select auth.uid()) on conflict(user_id,deduplication_key) where deduplication_key is not null do nothing$$;
revoke all on function private.notify_station(uuid,text,text,uuid,text,text,text,text) from public,anon,authenticated;

create function public.save_handover(target_station uuid,target_shift uuid,target_date date,general_text text,next_text text,items jsonb,participant_ids uuid[] default '{}') returns uuid language plpgsql security definer set search_path='' as $$declare hid uuid;item jsonb;begin if not private.has_permission_in_scope('handovers.create',target_station) then raise exception 'Devir teslim yetkiniz yok';end if;if target_date not between current_date-1 and current_date+1 then raise exception 'Tarih geçersiz';end if;insert into public.shift_handovers(station_id,shift_id,handover_date,created_by,general_note,next_shift_note) values(target_station,target_shift,target_date,(select auth.uid()),nullif(trim(general_text),''),nullif(trim(next_text),'')) on conflict(station_id,shift_id,handover_date) where deleted_at is null do update set general_note=excluded.general_note,next_shift_note=excluded.next_shift_note,updated_at=now(),version=public.shift_handovers.version+1 where public.shift_handovers.status='draft' and public.shift_handovers.created_by=(select auth.uid()) returning id into hid;if hid is null then raise exception 'Bu vardiya teslimi düzenlenemez';end if;delete from public.shift_handover_items where handover_id=hid;for item in select * from jsonb_array_elements(coalesce(items,'[]')) loop insert into public.shift_handover_items(handover_id,section_key,condition,note,sort_order) values(hid,item->>'key',item->>'condition',nullif(trim(item->>'note'),''),coalesce((item->>'order')::int,0));end loop;delete from public.shift_handover_participants where handover_id=hid;insert into public.shift_handover_participants select hid,u,'mentioned' from unnest(coalesce(participant_ids,'{}'))u where exists(select 1 from public.user_station_assignments a where a.station_id=target_station and a.user_id=u);insert into public.shift_handover_events(handover_id,actor_id,event_type) values(hid,(select auth.uid()),'draft_saved');return hid;end$$;
create function public.submit_handover(target_handover uuid,media_ids uuid[] default '{}') returns void language plpgsql security definer set search_path='' as $$declare h public.shift_handovers;critical boolean;begin select * into h from public.shift_handovers where id=target_handover and deleted_at is null for update;if h.id is null or h.status<>'draft' then raise exception 'Teslim gönderilemez';end if;if not (h.created_by=(select auth.uid()) and private.has_permission_in_scope('handovers.create',h.station_id)) and not private.has_permission_in_scope('handovers.override',h.station_id) then raise exception 'Yetkiniz yok';end if;if not exists(select 1 from public.shift_handover_items where handover_id=h.id) then raise exception 'Teslim bölümleri eksik';end if;if exists(select 1 from unnest(coalesce(media_ids,'{}'))m where not exists(select 1 from public.media_assets a where a.id=m and a.station_id=h.station_id and a.owner_id=(select auth.uid()) and a.deleted_at is null)) then raise exception 'Geçersiz medya';end if;insert into public.shift_handover_media select h.id,m from unnest(coalesce(media_ids,'{}'))m on conflict do nothing;update public.shift_handovers set status='submitted',submitted_at=now(),updated_at=now(),version=version+1 where id=h.id;insert into public.shift_handover_events(handover_id,actor_id,event_type)values(h.id,(select auth.uid()),'submitted');select exists(select 1 from public.shift_handover_items where handover_id=h.id and condition='issue') into critical;perform private.notify_station(h.station_id,'handover_submitted','handover',h.id,case when critical then 'Kritik vardiya teslimi' else 'Yeni vardiya teslimi' end,coalesce(h.next_shift_note,'Devir teslim kaydı hazır.'),case when critical then 'urgent' else 'normal' end,'handover:'||h.id);end$$;
create function public.acknowledge_handover(target_handover uuid) returns void language plpgsql security definer set search_path='' as $$declare h public.shift_handovers;begin select * into h from public.shift_handovers where id=target_handover and deleted_at is null for update;if h.id is null or h.status not in('submitted','acknowledged') or not private.has_permission_in_scope('handovers.acknowledge',h.station_id) then raise exception 'Teslim onaylanamaz';end if;insert into public.shift_handover_acknowledgements values(h.id,(select auth.uid()),now()) on conflict do nothing;update public.shift_handovers set status='acknowledged',updated_at=now(),version=version+1 where id=h.id and status='submitted';insert into public.shift_handover_events(handover_id,actor_id,event_type)values(h.id,(select auth.uid()),'acknowledged');end$$;

create function public.ensure_checklist_runs(target_station uuid,target_date date,target_shift uuid default null) returns integer language plpgsql security definer set search_path='' as $$declare count_created int;begin if not private.has_permission_in_scope('checklists.view',target_station) then raise exception 'Yetkiniz yok';end if;insert into public.checklist_runs(template_id,station_id,shift_id,run_date) select t.id,target_station,t.shift_id,target_date from public.checklist_templates t join public.stations s on s.id=target_station where t.is_active and t.deleted_at is null and (target_shift is null or t.shift_id is null or t.shift_id=target_shift) and (t.scope_type='global' or (t.scope_type='station' and t.station_id=target_station) or (t.scope_type='region' and t.region_id=s.region_id)) on conflict do nothing;get diagnostics count_created=row_count;insert into public.checklist_run_items(run_id,template_item_id) select r.id,i.id from public.checklist_runs r join public.checklist_template_items i on i.template_id=r.template_id where r.station_id=target_station and r.run_date=target_date on conflict do nothing;return count_created;end$$;
create function public.create_checklist_template(target_scope text,target_station uuid,target_region uuid,target_shift uuid,template_name text,template_description text,items jsonb) returns uuid language plpgsql security definer set search_path='' as $$declare tid uuid;item jsonb;begin if not private.has_permission_in_scope('checklists.create_template',target_station,target_region) then raise exception 'Şablon yetkiniz yok';end if;insert into public.checklist_templates(station_id,region_id,name,description,scope_type,shift_id,created_by)values(target_station,target_region,trim(template_name),nullif(trim(template_description),''),target_scope,target_shift,(select auth.uid()))returning id into tid;for item in select * from jsonb_array_elements(coalesce(items,'[]'))loop insert into public.checklist_template_items(template_id,title,description,sort_order,is_required,requires_note,requires_photo)values(tid,trim(item->>'title'),nullif(trim(item->>'description'),''),coalesce((item->>'order')::int,0),coalesce((item->>'required')::boolean,true),coalesce((item->>'requiresNote')::boolean,false),coalesce((item->>'requiresPhoto')::boolean,false));end loop;if not exists(select 1 from public.checklist_template_items where template_id=tid)then raise exception 'En az bir madde gerekli';end if;return tid;end$$;
create function public.update_checklist_item(target_item uuid,new_status text,new_note text,media_ids uuid[] default '{}') returns void language plpgsql security definer set search_path='' as $$declare i public.checklist_run_items;r public.checklist_runs;t public.checklist_template_items;begin select * into i from public.checklist_run_items where id=target_item for update;select * into r from public.checklist_runs where id=i.run_id;select * into t from public.checklist_template_items where id=i.template_item_id;if i.id is null or not private.has_permission_in_scope('checklists.execute',r.station_id) then raise exception 'Yetkiniz yok';end if;if new_status not in('pending','completed','skipped','issue') then raise exception 'Durum geçersiz';end if;if t.requires_note and nullif(trim(new_note),'') is null then raise exception 'Not zorunlu';end if;if t.requires_photo and cardinality(coalesce(media_ids,'{}'))=0 and not exists(select 1 from public.checklist_run_item_media where run_item_id=i.id) then raise exception 'Fotoğraf zorunlu';end if;insert into public.checklist_run_item_media select i.id,m from unnest(coalesce(media_ids,'{}'))m join public.media_assets a on a.id=m and a.station_id=r.station_id and a.owner_id=(select auth.uid()) and a.deleted_at is null on conflict do nothing;update public.checklist_run_items set status=new_status,note=nullif(trim(new_note),''),completed_by=case when new_status='pending' then null else (select auth.uid()) end,completed_at=case when new_status='pending' then null else now() end,updated_at=now() where id=i.id;update public.checklist_runs set status='in_progress',started_at=coalesce(started_at,now()),updated_at=now() where id=r.id and status='pending';if new_status='issue' then perform private.notify_station(r.station_id,'checklist_issue','checklist',r.id,'Checklist sorunu bildirildi',t.title,'important','checklist_issue:'||i.id);end if;end$$;
create function public.complete_checklist(target_run uuid) returns void language plpgsql security definer set search_path='' as $$declare r public.checklist_runs;begin select * into r from public.checklist_runs where id=target_run for update;if r.id is null or not private.has_permission_in_scope('checklists.execute',r.station_id) then raise exception 'Yetkiniz yok';end if;if exists(select 1 from public.checklist_run_items i join public.checklist_template_items t on t.id=i.template_item_id where i.run_id=r.id and t.is_required and i.status not in('completed','issue')) then raise exception 'Zorunlu maddeler tamamlanmadı';end if;update public.checklist_runs set status='completed',completed_at=now(),updated_at=now() where id=r.id;end$$;

create function public.create_issue(target_station uuid,issue_title text,issue_description text,issue_category text,issue_priority text,target_assignee uuid default null,media_ids uuid[] default '{}') returns uuid language plpgsql security definer set search_path='' as $$declare iid uuid;begin if not private.has_permission_in_scope('issues.create',target_station) then raise exception 'Arıza oluşturma yetkiniz yok';end if;if target_assignee is not null and (not private.has_permission_in_scope('issues.assign',target_station) or not exists(select 1 from public.user_station_assignments where station_id=target_station and user_id=target_assignee)) then raise exception 'Atama geçersiz';end if;insert into public.station_issues(station_id,created_by,title,description,category,priority,assigned_to)values(target_station,(select auth.uid()),trim(issue_title),trim(issue_description),trim(issue_category),issue_priority,target_assignee)returning id into iid;insert into public.station_issue_media select iid,m from unnest(coalesce(media_ids,'{}'))m join public.media_assets a on a.id=m and a.station_id=target_station and a.owner_id=(select auth.uid()) and a.deleted_at is null;insert into public.station_issue_events(issue_id,actor_id,event_type,body)values(iid,(select auth.uid()),'created',trim(issue_description));if issue_priority='critical' then perform private.notify_station(target_station,'critical_issue','issue',iid,'Kritik arıza',trim(issue_title),'urgent','critical_issue:'||iid);end if;if target_assignee is not null then perform private.notify_station(target_station,'issue_assigned','issue',iid,'Arıza atandı',trim(issue_title),'important','issue_assigned:'||iid);end if;return iid;end$$;
create function public.add_issue_event(target_issue uuid,event_body text) returns void language plpgsql security definer set search_path='' as $$declare i public.station_issues;begin select * into i from public.station_issues where id=target_issue and deleted_at is null;if i.id is null or not private.has_permission_in_scope('issues.edit',i.station_id) then raise exception 'Yetkiniz yok';end if;insert into public.station_issue_events(issue_id,actor_id,event_type,body)values(i.id,(select auth.uid()),'note',trim(event_body));end$$;
create function public.transition_issue(target_issue uuid,new_status text,resolution_note text default null) returns void language plpgsql security definer set search_path='' as $$declare i public.station_issues;begin select * into i from public.station_issues where id=target_issue and deleted_at is null for update;if i.id is null then raise exception 'Arıza bulunamadı';end if;if new_status='resolved' and not private.has_permission_in_scope('issues.resolve',i.station_id) then raise exception 'Çözme yetkiniz yok';elsif new_status='closed' and (i.status<>'resolved' or not private.has_permission_in_scope('issues.close',i.station_id)) then raise exception 'Kapatma yetkiniz yok';elsif new_status not in('investigating','waiting_service','resolved','closed','cancelled') or (new_status not in('resolved','closed') and not private.has_permission_in_scope('issues.edit',i.station_id)) then raise exception 'Durum değiştirilemez';end if;update public.station_issues set status=new_status,resolved_at=case when new_status='resolved' then now() else resolved_at end,closed_at=case when new_status='closed' then now() else closed_at end,updated_at=now(),version=version+1 where id=i.id;insert into public.station_issue_events(issue_id,actor_id,event_type,body,metadata)values(i.id,(select auth.uid()),new_status,nullif(trim(resolution_note),''),jsonb_build_object('from',i.status,'to',new_status));perform private.notify_station(i.station_id,'issue_'||new_status,'issue',i.id,case new_status when 'resolved' then 'Arıza çözüldü' when 'closed' then 'Arıza kapatıldı' else 'Arıza güncellendi' end,i.title,'normal','issue:'||i.id||':'||new_status);end$$;
create function public.delete_issue(target_issue uuid) returns void language plpgsql security definer set search_path='' as $$declare s uuid;begin select station_id into s from public.station_issues where id=target_issue and deleted_at is null for update;if s is null or not private.has_permission_in_scope('issues.delete',s) then raise exception 'Silme yetkiniz yok';end if;update public.station_issues set deleted_at=now(),updated_at=now(),version=version+1 where id=target_issue;insert into public.station_issue_events(issue_id,actor_id,event_type)values(target_issue,(select auth.uid()),'deleted');end$$;

create function public.get_station_operations(target_station uuid,target_date date default current_date) returns jsonb language sql stable security definer set search_path='' as $$select case when private.can_access_station(target_station) then jsonb_build_object('tasks_total',(select count(*) from public.tasks where station_id=target_station and deleted_at is null and due_date::date=target_date),'tasks_completed',(select count(*) from public.tasks where station_id=target_station and deleted_at is null and due_date::date=target_date and status='completed'),'tasks_overdue',(select count(*) from public.tasks where station_id=target_station and deleted_at is null and due_date<now() and status not in('completed','cancelled')),'checklists_total',(select count(*) from public.checklist_runs where station_id=target_station and run_date=target_date),'checklists_completed',(select count(*) from public.checklist_runs where station_id=target_station and run_date=target_date and status='completed'),'open_issues',(select count(*) from public.station_issues where station_id=target_station and deleted_at is null and status not in('closed','cancelled')),'critical_issues',(select count(*) from public.station_issues where station_id=target_station and deleted_at is null and priority='critical' and status not in('closed','cancelled')),'handovers',(select count(*) from public.shift_handovers where station_id=target_station and handover_date=target_date and deleted_at is null),'unread_handovers',(select count(*) from public.shift_handovers h where h.station_id=target_station and h.handover_date=target_date and h.status='submitted' and h.deleted_at is null and not exists(select 1 from public.shift_handover_acknowledgements a where a.handover_id=h.id and a.user_id=(select auth.uid()))),'operations',(select count(*) from public.operation_posts where station_id=target_station and deleted_at is null and created_at::date=target_date)) else null end$$;
create function public.save_daily_report_note(target_station uuid,target_date date,note_content text) returns uuid language plpgsql security definer set search_path='' as $$declare nid uuid;begin if not private.has_permission_in_scope('daily_reports.note',target_station) then raise exception 'Not yetkiniz yok';end if;insert into public.station_daily_report_notes(station_id,report_date,created_by,content)values(target_station,target_date,(select auth.uid()),trim(note_content))returning id into nid;return nid;end$$;

do $$declare f regprocedure;begin foreach f in array array['public.save_handover(uuid,uuid,date,text,text,jsonb,uuid[])'::regprocedure,'public.submit_handover(uuid,uuid[])'::regprocedure,'public.acknowledge_handover(uuid)'::regprocedure,'public.ensure_checklist_runs(uuid,date,uuid)'::regprocedure,'public.create_checklist_template(text,uuid,uuid,uuid,text,text,jsonb)'::regprocedure,'public.update_checklist_item(uuid,text,text,uuid[])'::regprocedure,'public.complete_checklist(uuid)'::regprocedure,'public.create_issue(uuid,text,text,text,text,uuid,uuid[])'::regprocedure,'public.add_issue_event(uuid,text)'::regprocedure,'public.transition_issue(uuid,text,text)'::regprocedure,'public.delete_issue(uuid)'::regprocedure,'public.get_station_operations(uuid,date)'::regprocedure,'public.save_daily_report_note(uuid,date,text)'::regprocedure] loop execute format('revoke all on function %s from public,anon',f);execute format('grant execute on function %s to authenticated',f);end loop;end$$;
create policy phase6_media_asset_insert on public.media_assets for insert to authenticated with check(bucket='operation-media' and owner_id=(select auth.uid()) and uploaded_by=(select auth.uid()) and station_id is not null and private.can_access_station(station_id) and storage_path like 'phase6/'||station_id::text||'/%');
create policy phase6_storage_insert on storage.objects for insert to authenticated with check(bucket_id='operation-media' and (storage.foldername(name))[1]='phase6' and (storage.foldername(name))[2]~*'^[0-9a-f-]{36}$' and private.can_access_station(((storage.foldername(name))[2])::uuid) and (storage.foldername(name))[3]=(select auth.uid())::text);
create policy phase6_storage_select on storage.objects for select to authenticated using(bucket_id='operation-media' and (storage.foldername(name))[1]='phase6' and (storage.foldername(name))[2]~*'^[0-9a-f-]{36}$' and private.can_access_station(((storage.foldername(name))[2])::uuid));
create trigger audit_handovers after insert or update or delete on public.shift_handovers for each row execute function private.audit_change();
create trigger audit_checklist_templates after insert or update or delete on public.checklist_templates for each row execute function private.audit_change();
create trigger audit_checklist_runs after insert or update or delete on public.checklist_runs for each row execute function private.audit_change();
create trigger audit_station_issues after insert or update or delete on public.station_issues for each row execute function private.audit_change();
create trigger audit_daily_notes after insert or update or delete on public.station_daily_report_notes for each row execute function private.audit_change();
