create function private.edit_task(target_task uuid,new_title text,new_description text,new_priority text,new_due_date timestamptz,new_shift uuid)
returns void language plpgsql security definer set search_path='' as $$
declare t public.tasks;assignee uuid;new_version integer;begin select * into t from public.tasks where id=target_task and deleted_at is null for update;if t.id is null then raise exception 'Görev bulunamadı';end if;if not private.has_permission_in_scope('tasks.edit',t.station_id) then raise exception 'Görev düzenleme yetkiniz yok';end if;if t.status in('completed','cancelled') then raise exception 'Kapalı görev düzenlenemez';end if;if char_length(trim(new_title)) not between 3 and 160 or new_priority not in('normal','important','urgent') then raise exception 'Görev alanlarını kontrol edin';end if;update public.tasks set title=trim(new_title),description=nullif(trim(new_description),''),priority=new_priority,due_date=new_due_date,shift_id=new_shift,updated_at=now(),version=version+1 where id=target_task returning version into new_version;insert into public.task_events(task_id,actor_id,event_type,metadata) values(target_task,(select auth.uid()),'edited',jsonb_build_object('version',new_version));for assignee in select user_id from public.task_assignees where task_id=target_task loop perform private.task_notify(assignee,target_task,'task_changed','Görev güncellendi',trim(new_title),'task_changed:'||target_task||':'||assignee||':'||new_version);end loop;end$$;
create function private.reopen_task(target_task uuid) returns void language plpgsql security definer set search_path='' as $$
declare t public.tasks;assignee uuid;begin select * into t from public.tasks where id=target_task and deleted_at is null for update;if t.id is null or t.status not in('rejected','completed') then raise exception 'Görev yeniden açılamaz';end if;if not private.has_permission_in_scope('tasks.reopen',t.station_id) then raise exception 'Yeniden açma yetkiniz yok';end if;update public.tasks set status='in_progress',completed_at=null,updated_at=now(),version=version+1 where id=target_task;update public.task_assignees set status='in_progress',completed_at=null where task_id=target_task;insert into public.task_events(task_id,actor_id,event_type) values(target_task,(select auth.uid()),'reopened');for assignee in select user_id from public.task_assignees where task_id=target_task loop perform private.task_notify(assignee,target_task,'task_reopened','Görev yeniden açıldı',t.title,'task_reopened:'||target_task||':'||assignee||':'||(t.version+1));end loop;end$$;
create function private.delete_task(target_task uuid) returns void language plpgsql security definer set search_path='' as $$declare t public.tasks;begin select * into t from public.tasks where id=target_task and deleted_at is null for update;if t.id is null then raise exception 'Görev bulunamadı';end if;if not private.has_permission_in_scope('tasks.delete',t.station_id) then raise exception 'Görev silme yetkiniz yok';end if;update public.tasks set deleted_at=now(),deleted_by=(select auth.uid()),updated_at=now(),version=version+1 where id=target_task;insert into public.task_events(task_id,actor_id,event_type,metadata) values(target_task,(select auth.uid()),'cancelled',jsonb_build_object('soft_delete',true));end$$;

revoke all on function private.edit_task(uuid,text,text,text,timestamptz,uuid),private.reopen_task(uuid),private.delete_task(uuid) from public,anon;
grant execute on function private.edit_task(uuid,text,text,text,timestamptz,uuid),private.reopen_task(uuid),private.delete_task(uuid) to authenticated;
create function public.edit_task(target_task uuid,new_title text,new_description text,new_priority text,new_due_date timestamptz,new_shift uuid) returns void language sql volatile security invoker set search_path='' as $$select private.edit_task(target_task,new_title,new_description,new_priority,new_due_date,new_shift)$$;
create function public.reopen_task(target_task uuid) returns void language sql volatile security invoker set search_path='' as $$select private.reopen_task(target_task)$$;
create function public.delete_task(target_task uuid) returns void language sql volatile security invoker set search_path='' as $$select private.delete_task(target_task)$$;
revoke all on function public.edit_task(uuid,text,text,text,timestamptz,uuid),public.reopen_task(uuid),public.delete_task(uuid) from public,anon;
grant execute on function public.edit_task(uuid,text,text,text,timestamptz,uuid),public.reopen_task(uuid),public.delete_task(uuid) to authenticated;
