-- Phase 5: scoped chat, durable files/news, push subscriptions and idempotency.
alter table public.messages rename column author_id to sender_id;
alter table public.messages rename column body to message;
alter table public.messages add column station_id uuid references public.stations(id);
update public.messages m set station_id=c.station_id from public.channels c where c.id=m.channel_id and m.station_id is null;
alter table public.messages alter column station_id set not null;
alter table public.messages add column reply_to_message_id uuid references public.messages(id);
alter table public.messages add column message_type text not null default 'text' check(message_type in('text','image','file','system'));
alter table public.messages add column media_id uuid references public.media_assets(id);
alter table public.messages add column deleted_at timestamptz;
alter table public.messages add column deleted_by uuid references auth.users(id);
alter table public.messages add column version integer not null default 1 check(version>0);
alter table public.messages add column metadata jsonb not null default '{}' check(jsonb_typeof(metadata)='object');
alter table public.messages add constraint messages_content_check check((message_type='text' and char_length(message) between 1 and 4000) or (message_type<>'text' and media_id is not null));
create index messages_station_cursor_idx on public.messages(station_id,created_at desc,id desc);
create index messages_search_idx on public.messages using gin(to_tsvector('simple',message));

create table public.station_files(id uuid primary key default gen_random_uuid(),station_id uuid not null references public.stations(id),created_by uuid not null references public.profiles(id),name text not null check(char_length(name) between 2 and 180),description text check(description is null or char_length(description)<=2000),category text not null check(category in('pdf','word','excel','video','zip','image','text','other')),media_id uuid not null references public.media_assets(id),cover_media_id uuid references public.media_assets(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,deleted_by uuid references auth.users(id),version integer not null default 1 check(version>0));
create index station_files_cursor_idx on public.station_files(station_id,created_at desc,id desc) where deleted_at is null;
alter table public.station_files enable row level security;revoke all on public.station_files from anon,authenticated;grant select on public.station_files to authenticated;

create table public.news_posts(id uuid primary key default gen_random_uuid(),title text not null check(char_length(title) between 3 and 180),summary text not null check(char_length(summary) between 3 and 500),content text not null check(char_length(content) between 3 and 12000),cover_media_id uuid references public.media_assets(id),scope_type text not null check(scope_type in('global','region','station')),region_id uuid references public.regions(id),station_id uuid references public.stations(id),status text not null default 'draft' check(status in('draft','scheduled','published','archived')),publish_at timestamptz,expires_at timestamptz,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz,deleted_by uuid references auth.users(id),version integer not null default 1 check(version>0),check((scope_type='global' and region_id is null and station_id is null)or(scope_type='region' and region_id is not null and station_id is null)or(scope_type='station' and station_id is not null and region_id is null)),check(expires_at is null or publish_at is null or expires_at>publish_at));
create index news_visible_cursor_idx on public.news_posts(status,publish_at desc,id desc) where deleted_at is null;
alter table public.news_posts enable row level security;revoke all on public.news_posts from anon,authenticated;grant select on public.news_posts to authenticated;

create table public.push_subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,endpoint text not null unique,p256dh text not null,auth text not null,user_agent text,created_at timestamptz not null default now(),last_used_at timestamptz,revoked_at timestamptz,unique(user_id,endpoint));
create index push_subscriptions_user_idx on public.push_subscriptions(user_id) where revoked_at is null;
alter table public.push_subscriptions enable row level security;revoke all on public.push_subscriptions from anon,authenticated;grant select on public.push_subscriptions to authenticated;

create table public.mutation_idempotency(user_id uuid not null references public.profiles(id) on delete cascade,idempotency_key uuid not null,mutation_type text not null check(char_length(mutation_type) between 2 and 80),created_at timestamptz not null default now(),expires_at timestamptz not null default now()+interval '7 days',primary key(user_id,idempotency_key));
alter table public.mutation_idempotency enable row level security;revoke all on public.mutation_idempotency from anon,authenticated;grant select on public.mutation_idempotency to authenticated;

insert into public.permissions(name,slug,category,scope_type,is_system_permission) values
('Mesajları Gör','messages.view','Sohbet','station',true),('Mesaj Gönder','messages.send','Sohbet','station',true),('Kendi Mesajını Düzenle','messages.edit_own','Sohbet','station',true),('Kendi Mesajını Sil','messages.delete_own','Sohbet','station',true),('Sohbeti Yönet','messages.moderate','Sohbet','station',true)
on conflict(slug) do update set name=excluded.name,category=excluded.category,scope_type=excluded.scope_type,is_system_permission=true;
with mapping(old_slug,new_slug) as(values('general_chat.view','messages.view'),('general_chat.send','messages.send'),('general_chat.edit_own','messages.edit_own')) insert into public.role_permissions(role_id,permission_id,scope_kind,granted) select distinct rp.role_id,np.id,rp.scope_kind,rp.granted from public.role_permissions rp join public.permissions op on op.id=rp.permission_id join mapping m on m.old_slug=op.slug join public.permissions np on np.slug=m.new_slug on conflict do nothing;
with rs(slug) as(values('regional_manager'),('station_manager'),('assistant_station_manager')) insert into public.role_permissions(role_id,permission_id,scope_kind,granted) select r.id,p.id,'assigned',true from rs join public.roles r using(slug) cross join public.permissions p where p.slug in('messages.delete_own','messages.moderate','files.delete','news.edit','news.delete','news.publish') on conflict do nothing;

create function private.can_view_message(target_message uuid,check_user uuid default auth.uid()) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.messages m where m.id=target_message and private.has_permission_in_scope('messages.view',m.station_id,null,check_user) and private.can_access_station(m.station_id,check_user))$$;
drop policy if exists station_messages on public.messages;create policy messages_scoped_read on public.messages for select to authenticated using(private.can_view_message(id));
drop policy if exists station_channels on public.channels;create policy channels_scoped_read on public.channels for select to authenticated using(private.can_access_station(station_id) and private.has_permission_in_scope('messages.view',station_id));
create policy station_files_read on public.station_files for select to authenticated using(deleted_at is null and private.can_access_station(station_id) and private.has_permission_in_scope('files.view',station_id));
create policy push_subscriptions_own_read on public.push_subscriptions for select to authenticated using(user_id=(select auth.uid()));
create policy mutation_idempotency_own_read on public.mutation_idempotency for select to authenticated using(user_id=(select auth.uid()));

create function private.can_view_news(n public.news_posts,check_user uuid default auth.uid()) returns boolean language sql stable security definer set search_path='' as $$select n.deleted_at is null and ((n.created_by=check_user and n.status in('draft','scheduled')) or (n.status='published' and n.publish_at<=now() and (n.expires_at is null or n.expires_at>now()) and private.has_permission_in_scope('news.view',n.station_id,n.region_id,check_user) and (n.scope_type='global' or (n.scope_type='station' and private.can_access_station(n.station_id,check_user)) or (n.scope_type='region' and (private.is_op(check_user) or exists(select 1 from public.user_region_assignments a where a.user_id=check_user and a.region_id=n.region_id) or exists(select 1 from public.user_station_assignments a join public.stations s on s.id=a.station_id where a.user_id=check_user and s.region_id=n.region_id)))))$$;
create policy news_scoped_read on public.news_posts for select to authenticated using(private.can_view_news(news_posts));

create function private.ensure_general_channel(target_station uuid) returns uuid language plpgsql security definer set search_path='' as $$declare cid uuid;begin if not private.can_access_station(target_station) or not private.has_permission_in_scope('messages.view',target_station) then raise exception 'Sohbet erişiminiz yok';end if;insert into public.channels(station_id,name,slug,created_by) values(target_station,'Genel','general',(select auth.uid())) on conflict(station_id,slug) do update set is_active=true returning id into cid;return cid;end$$;
create function private.send_message(target_station uuid,message_text text,reply_to uuid default null,idempotency_key uuid default gen_random_uuid()) returns uuid language plpgsql security definer set search_path='' as $$declare cid uuid;mid uuid;begin if not private.can_access_station(target_station) or not private.has_permission_in_scope('messages.send',target_station) then raise exception 'Mesaj gönderme yetkiniz yok';end if;if char_length(trim(message_text)) not between 1 and 4000 then raise exception 'Mesajı kontrol edin';end if;if reply_to is not null and not exists(select 1 from public.messages where id=reply_to and station_id=target_station) then raise exception 'Yanıtlanan mesaj geçersiz';end if;insert into public.mutation_idempotency(user_id,idempotency_key,mutation_type) values((select auth.uid()),idempotency_key,'message.send') on conflict do nothing;if not found then select id into mid from public.messages where sender_id=(select auth.uid()) and station_id=target_station and metadata->>'idempotency_key'=idempotency_key::text limit 1;return mid;end if;select private.ensure_general_channel(target_station) into cid;insert into public.messages(channel_id,station_id,sender_id,message,reply_to_message_id,metadata) values(cid,target_station,(select auth.uid()),trim(message_text),reply_to,jsonb_build_object('idempotency_key',idempotency_key)) returning id into mid;return mid;end$$;
create function private.edit_message(target_message uuid,new_message text) returns void language plpgsql security definer set search_path='' as $$declare m public.messages;begin select * into m from public.messages where id=target_message for update;if m.id is null or m.deleted_at is not null then raise exception 'Mesaj bulunamadı';end if;if not ((m.sender_id=(select auth.uid()) and now()<=m.created_at+interval '60 minutes' and private.has_permission_in_scope('messages.edit_own',m.station_id)) or private.has_permission_in_scope('messages.moderate',m.station_id)) then raise exception 'Düzenleme süresi doldu veya yetkiniz yok';end if;update public.messages set message=trim(new_message),updated_at=now(),version=version+1 where id=target_message;if m.sender_id<>(select auth.uid()) or now()>m.created_at+interval '60 minutes' then insert into public.audit_logs(actor_user_id,action,target_type,target_id,station_id,metadata) values((select auth.uid()),'moderate_edit','messages',target_message::text,m.station_id,jsonb_build_object('content_redacted',true));end if;end$$;
create function private.delete_message(target_message uuid) returns void language plpgsql security definer set search_path='' as $$declare m public.messages;begin select * into m from public.messages where id=target_message for update;if m.id is null then raise exception 'Mesaj bulunamadı';end if;if not ((m.sender_id=(select auth.uid()) and private.has_permission_in_scope('messages.delete_own',m.station_id)) or private.has_permission_in_scope('messages.moderate',m.station_id)) then raise exception 'Mesaj silme yetkiniz yok';end if;update public.messages set deleted_at=now(),deleted_by=(select auth.uid()),updated_at=now(),version=version+1 where id=target_message;insert into public.audit_logs(actor_user_id,action,target_type,target_id,station_id,metadata) values((select auth.uid()),case when m.sender_id=(select auth.uid()) then 'soft_delete' else 'moderate_delete' end,'messages',target_message::text,m.station_id,jsonb_build_object('content_redacted',true));end$$;
create function public.list_messages(target_station uuid,search_text text default null,cursor_created timestamptz default null,cursor_id uuid default null,page_size integer default 40) returns table(id uuid,station_id uuid,sender_id uuid,sender_name text,sender_roles text[],message text,message_type text,reply_to_message_id uuid,reply_preview text,created_at timestamptz,updated_at timestamptz,deleted_at timestamptz,is_mine boolean,can_edit boolean,can_delete boolean) language sql stable security invoker set search_path='' as $$select m.id,m.station_id,m.sender_id,trim(p.first_name||' '||p.last_name),coalesce((select array_agg(distinct r.name order by r.name) from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=m.sender_id),'{}'),case when m.deleted_at is null then m.message else 'Bu mesaj silindi.' end,m.message_type,m.reply_to_message_id,case when rm.deleted_at is null then left(rm.message,140) else 'Bu mesaj silindi.' end,m.created_at,m.updated_at,m.deleted_at,m.sender_id=(select auth.uid()),m.deleted_at is null and ((m.sender_id=(select auth.uid()) and now()<=m.created_at+interval '60 minutes' and private.has_permission_in_scope('messages.edit_own',m.station_id)) or private.has_permission_in_scope('messages.moderate',m.station_id)),m.deleted_at is null and ((m.sender_id=(select auth.uid()) and private.has_permission_in_scope('messages.delete_own',m.station_id)) or private.has_permission_in_scope('messages.moderate',m.station_id)) from public.messages m join public.profiles p on p.id=m.sender_id left join public.messages rm on rm.id=m.reply_to_message_id where m.station_id=target_station and private.can_view_message(m.id) and (search_text is null or search_text='' or m.message ilike '%'||search_text||'%' or trim(p.first_name||' '||p.last_name) ilike '%'||search_text||'%') and (cursor_created is null or (m.created_at,m.id)<(cursor_created,coalesce(cursor_id,'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid))) order by m.created_at desc,m.id desc limit least(greatest(page_size,1),80)$$;

create function private.create_station_file(target_station uuid,file_name text,file_description text,file_category text,target_media uuid,target_cover uuid default null) returns uuid language plpgsql security definer set search_path='' as $$declare fid uuid;begin if not private.has_permission_in_scope('files.upload',target_station) then raise exception 'Dosya ekleme yetkiniz yok';end if;if not exists(select 1 from public.media_assets m where m.id=target_media and m.owner_id=(select auth.uid()) and m.station_id=target_station and m.bucket='shared-content' and m.deleted_at is null) then raise exception 'Geçersiz dosya';end if;insert into public.station_files(station_id,created_by,name,description,category,media_id,cover_media_id) values(target_station,(select auth.uid()),trim(file_name),nullif(trim(file_description),''),file_category,target_media,target_cover) returning id into fid;return fid;end$$;
create function private.delete_station_file(target_file uuid) returns void language plpgsql security definer set search_path='' as $$declare f public.station_files;begin select * into f from public.station_files where id=target_file and deleted_at is null for update;if f.id is null then raise exception 'Dosya bulunamadı';end if;if not private.has_permission_in_scope('files.delete',f.station_id) then raise exception 'Dosya silme yetkiniz yok';end if;update public.station_files set deleted_at=now(),deleted_by=(select auth.uid()),updated_at=now(),version=version+1 where id=target_file;end$$;
create function public.list_station_files(target_station uuid,search_text text default null,category_filter text default null,cursor_created timestamptz default null,cursor_id uuid default null,page_size integer default 20) returns table(id uuid,name text,description text,category text,created_at timestamptz,creator_name text,media_id uuid,bucket text,storage_path text,original_name text,mime_type text,size_bytes bigint,can_delete boolean) language sql stable security invoker set search_path='' as $$select f.id,f.name,f.description,f.category,f.created_at,trim(p.first_name||' '||p.last_name),m.id,m.bucket,m.storage_path,m.original_name,m.mime_type,m.size_bytes,private.has_permission_in_scope('files.delete',f.station_id) from public.station_files f join public.profiles p on p.id=f.created_by join public.media_assets m on m.id=f.media_id where f.station_id=target_station and f.deleted_at is null and private.can_access_station(f.station_id) and private.has_permission_in_scope('files.view',f.station_id) and (category_filter is null or category_filter='' or f.category=category_filter) and (search_text is null or search_text='' or f.name ilike '%'||search_text||'%' or coalesce(f.description,'') ilike '%'||search_text||'%' or trim(p.first_name||' '||p.last_name) ilike '%'||search_text||'%') and (cursor_created is null or (f.created_at,f.id)<(cursor_created,coalesce(cursor_id,'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid))) order by f.created_at desc,f.id desc limit least(greatest(page_size,1),50)$$;

create function private.create_news(news_title text,news_summary text,news_content text,target_scope text,target_region uuid,target_station uuid,target_status text,target_publish_at timestamptz,target_expires_at timestamptz,target_cover uuid default null) returns uuid language plpgsql security definer set search_path='' as $$declare nid uuid;begin if not private.has_permission_in_scope('news.create',target_station,target_region) then raise exception 'Haber oluşturma yetkiniz yok';end if;if target_status not in('draft','scheduled','published') then raise exception 'Geçersiz haber durumu';end if;if target_status<>'draft' and not private.has_permission_in_scope('news.publish',target_station,target_region) then raise exception 'Haber yayınlama yetkiniz yok';end if;if target_cover is not null and not exists(select 1 from public.media_assets m where m.id=target_cover and m.owner_id=(select auth.uid()) and m.bucket='shared-content' and m.deleted_at is null and m.metadata->>'news_scope'=target_scope and (target_scope='global' or (target_scope='station' and m.station_id=target_station) or (target_scope='region' and m.metadata->>'region_id'=target_region::text))) then raise exception 'Geçersiz haber kapağı';end if;insert into public.news_posts(title,summary,content,cover_media_id,scope_type,region_id,station_id,status,publish_at,expires_at,created_by) values(trim(news_title),trim(news_summary),trim(news_content),target_cover,target_scope,target_region,target_station,target_status,case when target_status='published' then coalesce(target_publish_at,now()) else target_publish_at end,target_expires_at,(select auth.uid())) returning id into nid;return nid;end$$;
create function private.update_news(target_news uuid,news_title text,news_summary text,news_content text,target_status text,target_publish_at timestamptz,target_expires_at timestamptz) returns void language plpgsql security definer set search_path='' as $$declare n public.news_posts;begin select * into n from public.news_posts where id=target_news and deleted_at is null for update;if n.id is null then raise exception 'Haber bulunamadı';end if;if not private.has_permission_in_scope('news.edit',n.station_id,n.region_id) then raise exception 'Haber düzenleme yetkiniz yok';end if;if target_status not in('draft','scheduled','published','archived') then raise exception 'Geçersiz haber durumu';end if;if target_status in('scheduled','published') and not private.has_permission_in_scope('news.publish',n.station_id,n.region_id) then raise exception 'Haber yayınlama yetkiniz yok';end if;update public.news_posts set title=trim(news_title),summary=trim(news_summary),content=trim(news_content),status=target_status,publish_at=case when target_status='published' then coalesce(target_publish_at,now()) else target_publish_at end,expires_at=target_expires_at,updated_at=now(),version=version+1 where id=target_news;end$$;
create function private.delete_news(target_news uuid) returns void language plpgsql security definer set search_path='' as $$declare n public.news_posts;begin select * into n from public.news_posts where id=target_news and deleted_at is null for update;if n.id is null then raise exception 'Haber bulunamadı';end if;if not private.has_permission_in_scope('news.delete',n.station_id,n.region_id) then raise exception 'Haber silme yetkiniz yok';end if;update public.news_posts set deleted_at=now(),deleted_by=(select auth.uid()),updated_at=now(),version=version+1 where id=target_news;end$$;
create function public.list_news(target_station uuid default null,page_size integer default 12) returns table(id uuid,title text,summary text,content text,scope_type text,publish_at timestamptz,expires_at timestamptz,creator_name text,cover_bucket text,cover_path text) language sql stable security invoker set search_path='' as $$select n.id,n.title,n.summary,n.content,n.scope_type,n.publish_at,n.expires_at,trim(p.first_name||' '||p.last_name),m.bucket,m.storage_path from public.news_posts n join public.profiles p on p.id=n.created_by left join public.media_assets m on m.id=n.cover_media_id where private.can_view_news(n) and (target_station is null or n.station_id=target_station or n.scope_type in('global','region')) order by n.publish_at desc,n.id desc limit least(greatest(page_size,1),50)$$;

create function private.save_push_subscription(subscription_endpoint text,subscription_p256dh text,subscription_auth text,agent text) returns uuid language plpgsql security definer set search_path='' as $$declare sid uuid;begin if not private.is_active_user() then raise exception 'Aktif kullanıcı gerekli';end if;if exists(select 1 from public.push_subscriptions where endpoint=subscription_endpoint and user_id<>(select auth.uid())) then raise exception 'Abonelik başka kullanıcıya ait';end if;insert into public.push_subscriptions(user_id,endpoint,p256dh,auth,user_agent,last_used_at,revoked_at) values((select auth.uid()),subscription_endpoint,subscription_p256dh,subscription_auth,left(agent,500),now(),null) on conflict(endpoint) do update set p256dh=excluded.p256dh,auth=excluded.auth,user_agent=excluded.user_agent,last_used_at=now(),revoked_at=null returning id into sid;insert into public.audit_logs(actor_user_id,action,target_type,target_id,metadata) values((select auth.uid()),'subscribe','push_subscriptions',sid::text,jsonb_build_object('endpoint_redacted',true));return sid;end$$;
create function private.revoke_push_subscription(subscription_endpoint text) returns void language plpgsql security definer set search_path='' as $$begin update public.push_subscriptions set revoked_at=now() where endpoint=subscription_endpoint and user_id=(select auth.uid());end$$;
create function private.reserve_mutation(idempotency_key uuid,mutation_type text) returns boolean language plpgsql security definer set search_path='' as $$begin insert into public.mutation_idempotency(user_id,idempotency_key,mutation_type) values((select auth.uid()),idempotency_key,mutation_type) on conflict do nothing;return found;end$$;

create function public.send_message(target_station uuid,message_text text,reply_to uuid default null,idempotency_key uuid default gen_random_uuid()) returns uuid language sql volatile security invoker set search_path='' as $$select private.send_message(target_station,message_text,reply_to,idempotency_key)$$;
create function public.edit_message(target_message uuid,new_message text) returns void language sql volatile security invoker set search_path='' as $$select private.edit_message(target_message,new_message)$$;
create function public.delete_message(target_message uuid) returns void language sql volatile security invoker set search_path='' as $$select private.delete_message(target_message)$$;
create function public.create_station_file(target_station uuid,file_name text,file_description text,file_category text,target_media uuid,target_cover uuid default null) returns uuid language sql volatile security invoker set search_path='' as $$select private.create_station_file(target_station,file_name,file_description,file_category,target_media,target_cover)$$;
create function public.delete_station_file(target_file uuid) returns void language sql volatile security invoker set search_path='' as $$select private.delete_station_file(target_file)$$;
create function public.create_news(news_title text,news_summary text,news_content text,target_scope text,target_region uuid,target_station uuid,target_status text,target_publish_at timestamptz,target_expires_at timestamptz,target_cover uuid default null) returns uuid language sql volatile security invoker set search_path='' as $$select private.create_news(news_title,news_summary,news_content,target_scope,target_region,target_station,target_status,target_publish_at,target_expires_at,target_cover)$$;
create function public.update_news(target_news uuid,news_title text,news_summary text,news_content text,target_status text,target_publish_at timestamptz,target_expires_at timestamptz) returns void language sql volatile security invoker set search_path='' as $$select private.update_news(target_news,news_title,news_summary,news_content,target_status,target_publish_at,target_expires_at)$$;
create function public.delete_news(target_news uuid) returns void language sql volatile security invoker set search_path='' as $$select private.delete_news(target_news)$$;
create function public.save_push_subscription(subscription_endpoint text,subscription_p256dh text,subscription_auth text,agent text) returns uuid language sql volatile security invoker set search_path='' as $$select private.save_push_subscription(subscription_endpoint,subscription_p256dh,subscription_auth,agent)$$;
create function public.revoke_push_subscription(subscription_endpoint text) returns void language sql volatile security invoker set search_path='' as $$select private.revoke_push_subscription(subscription_endpoint)$$;
create function public.reserve_mutation(idempotency_key uuid,mutation_type text) returns boolean language sql volatile security invoker set search_path='' as $$select private.reserve_mutation(idempotency_key,mutation_type)$$;

revoke all on function private.can_view_message(uuid,uuid),private.can_view_news(public.news_posts,uuid),private.ensure_general_channel(uuid),private.send_message(uuid,text,uuid,uuid),private.edit_message(uuid,text),private.delete_message(uuid),private.create_station_file(uuid,text,text,text,uuid,uuid),private.delete_station_file(uuid),private.create_news(text,text,text,text,uuid,uuid,text,timestamptz,timestamptz,uuid),private.update_news(uuid,text,text,text,text,timestamptz,timestamptz),private.delete_news(uuid),private.save_push_subscription(text,text,text,text),private.revoke_push_subscription(text),private.reserve_mutation(uuid,text) from public,anon,authenticated;
grant execute on function public.list_messages(uuid,text,timestamptz,uuid,integer),public.send_message(uuid,text,uuid,uuid),public.edit_message(uuid,text),public.delete_message(uuid),public.list_station_files(uuid,text,text,timestamptz,uuid,integer),public.create_station_file(uuid,text,text,text,uuid,uuid),public.delete_station_file(uuid),public.list_news(uuid,integer),public.create_news(text,text,text,text,uuid,uuid,text,timestamptz,timestamptz,uuid),public.update_news(uuid,text,text,text,text,timestamptz,timestamptz),public.delete_news(uuid),public.save_push_subscription(text,text,text,text),public.revoke_push_subscription(text),public.reserve_mutation(uuid,text) to authenticated;

drop policy if exists media_assets_insert on public.media_assets;
create policy media_assets_insert on public.media_assets for insert to authenticated with check(uploaded_by=(select auth.uid()) and owner_id=(select auth.uid()) and deleted_at is null and ((bucket='profile-media' and station_id is null)or(bucket='operation-media' and station_id is not null and(private.has_permission_in_scope('status_posts.create',station_id,null)or(storage_path like 'tasks/%' and exists(select 1 from public.tasks t join public.task_assignees ta on ta.task_id=t.id where t.id=(split_part(storage_path,'/',3))::uuid and t.station_id=media_assets.station_id and ta.user_id=(select auth.uid()) and t.deleted_at is null))))or(bucket='shared-content' and((storage_path like 'files/%' and station_id is not null and private.has_permission_in_scope('files.upload',station_id,null))or(metadata->>'announcement_scope'='global' and station_id is null and private.has_permission_in_scope('announcements.create'))or(metadata->>'announcement_scope'='region' and station_id is null and private.has_permission_in_scope('announcements.create',null,(metadata->>'region_id')::uuid))or(metadata->>'announcement_scope'='station' and station_id is not null and private.has_permission_in_scope('announcements.create',station_id,null))or(metadata->>'announcement_scope' is null and(storage_path not like 'files/%')and(station_id is null or private.has_permission_in_scope('files.upload',station_id,null))))or(bucket='brand-assets' and private.has_permission_in_scope('system.manage_settings'))));
create policy station_file_object_insert on storage.objects for insert to authenticated with check(bucket_id='shared-content' and name ~ '^files/[0-9a-f-]{36}/[0-9a-f-]{36}/[0-9a-f-]{36}/[0-9a-f-]{36}\.(pdf|docx|xlsx|mp4|webm|zip|jpg|jpeg|png|webp|txt)$' and (storage.foldername(name))[4]=(select auth.uid())::text and private.has_permission_in_scope('files.upload',((storage.foldername(name))[2])::uuid));
create policy station_file_object_select on storage.objects for select to authenticated using(bucket_id='shared-content' and (storage.foldername(name))[1]='files' and exists(select 1 from public.media_assets m join public.station_files f on f.media_id=m.id where m.storage_path=name and f.deleted_at is null and private.can_access_station(f.station_id) and private.has_permission_in_scope('files.view',f.station_id)));
create policy news_media_asset_insert on public.media_assets for insert to authenticated with check(bucket='shared-content' and uploaded_by=(select auth.uid()) and owner_id=(select auth.uid()) and deleted_at is null and metadata->>'news_scope' in('global','region','station') and ((metadata->>'news_scope'='global' and station_id is null and private.has_permission_in_scope('news.create'))or(metadata->>'news_scope'='region' and station_id is null and private.has_permission_in_scope('news.create',null,(metadata->>'region_id')::uuid))or(metadata->>'news_scope'='station' and station_id is not null and private.has_permission_in_scope('news.create',station_id,null))));
create policy content_media_asset_read on public.media_assets for select to authenticated using(deleted_at is null and (exists(select 1 from public.announcement_media am where am.media_id=media_assets.id and private.can_view_announcement(am.announcement_id))or exists(select 1 from public.news_posts n where n.cover_media_id=media_assets.id and private.can_view_news(n))));
create policy news_content_insert on storage.objects for insert to authenticated with check(bucket_id='shared-content' and name ~ '^news/(global|region|station)/([0-9a-f-]{36}|global)/[0-9a-f-]{36}/[0-9a-f-]{36}\.(jpg|jpeg|png|webp)$' and (storage.foldername(name))[4]=(select auth.uid())::text and (((storage.foldername(name))[2]='global' and private.has_permission_in_scope('news.create'))or((storage.foldername(name))[2]='station' and private.has_permission_in_scope('news.create',((storage.foldername(name))[3])::uuid,null))or((storage.foldername(name))[2]='region' and private.has_permission_in_scope('news.create',null,((storage.foldername(name))[3])::uuid))));
create policy news_content_select on storage.objects for select to authenticated using(bucket_id='shared-content' and (storage.foldername(name))[1]='news' and exists(select 1 from public.media_assets m join public.news_posts n on n.cover_media_id=m.id where m.storage_path=name and private.can_view_news(n)));

create trigger audit_station_files after insert or update or delete on public.station_files for each row execute function private.audit_change();
create trigger audit_news_posts after insert or update or delete on public.news_posts for each row execute function private.audit_change();
do $$begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='messages') then alter publication supabase_realtime add table public.messages;end if;end$$;
