-- Move sensitive implementations out of the Data API surface. Public names stay
-- unchanged for application compatibility and invoke the private functions.
create function private.get_my_profile()
returns table(id uuid,first_name text,last_name text,email text,status public.profile_status,avatar_url text,employee_number text,phone text,address text,emergency_phone text,employment_start_date date,employment_end_date date)
language sql stable security definer set search_path='' as $$select p.id,p.first_name,p.last_name,p.email,p.status,p.avatar_url,p.employee_number,pp.phone,pp.address,pp.emergency_phone,pp.employment_start_date,pp.employment_end_date from public.profiles p left join public.personnel_private pp on pp.user_id=p.id where p.id=(select auth.uid()) and p.deleted_at is null$$;
create function private.update_my_profile(new_phone text,new_address text,new_emergency_phone text,new_avatar_url text default null) returns void language plpgsql security definer set search_path='' as $$begin if not private.is_active_user() then raise exception 'Aktif kullanıcı gerekli';end if;if new_phone is not null and char_length(trim(new_phone)) not between 7 and 30 then raise exception 'Geçersiz telefon';end if;if new_emergency_phone is not null and char_length(trim(new_emergency_phone)) not between 7 and 30 then raise exception 'Geçersiz acil durum telefonu';end if;if new_address is not null and char_length(trim(new_address))>500 then raise exception 'Adres çok uzun';end if;insert into public.personnel_private(user_id,phone,address,emergency_phone,updated_by) values((select auth.uid()),nullif(trim(new_phone),''),nullif(trim(new_address),''),nullif(trim(new_emergency_phone),''),(select auth.uid())) on conflict(user_id) do update set phone=excluded.phone,address=excluded.address,emergency_phone=excluded.emergency_phone,updated_at=now(),updated_by=(select auth.uid());if new_avatar_url is not null then update public.profiles set avatar_url=nullif(trim(new_avatar_url),''),updated_at=now() where id=(select auth.uid());end if;end$$;
create function private.get_station_personnel(target_station uuid) returns table(user_id uuid,first_name text,last_name text,avatar_url text,role_name text,role_rank integer,phone text) language sql stable security definer set search_path='' as $$select p.id,p.first_name,p.last_name,p.avatar_url,r.name,r.role_rank,case when private.has_permission_in_scope('personnel.view_phone',target_station,null) then pp.phone else null end from public.user_station_assignments usa join public.profiles p on p.id=usa.user_id and p.status='active' and p.deleted_at is null left join lateral(select rr.name,rr.role_rank from public.user_roles ur join public.roles rr on rr.id=ur.role_id and rr.is_active where ur.user_id=p.id order by rr.role_rank,rr.name limit 1) r on true left join public.personnel_private pp on pp.user_id=p.id where usa.station_id=target_station and private.has_permission_in_scope('personnel.view_directory',target_station,null) order by coalesce(r.role_rank,1000),p.first_name,p.last_name$$;

create or replace function public.get_my_profile() returns table(id uuid,first_name text,last_name text,email text,status public.profile_status,avatar_url text,employee_number text,phone text,address text,emergency_phone text,employment_start_date date,employment_end_date date) language sql stable security invoker set search_path='' as $$select * from private.get_my_profile()$$;
create or replace function public.update_my_profile(new_phone text,new_address text,new_emergency_phone text,new_avatar_url text default null) returns void language sql volatile security invoker set search_path='' as $$select private.update_my_profile(new_phone,new_address,new_emergency_phone,new_avatar_url)$$;
create or replace function public.get_station_personnel(target_station uuid) returns table(user_id uuid,first_name text,last_name text,avatar_url text,role_name text,role_rank integer,phone text) language sql stable security invoker set search_path='' as $$select * from private.get_station_personnel(target_station)$$;
revoke all on function private.get_my_profile(),private.update_my_profile(text,text,text,text),private.get_station_personnel(uuid) from public,anon,authenticated;
grant execute on function public.get_my_profile(),public.update_my_profile(text,text,text,text),public.get_station_personnel(uuid) to authenticated;

drop policy if exists personnel_private_self_read on public.personnel_private;
drop policy if exists personnel_private_sensitive_read on public.personnel_private;
create policy personnel_private_read on public.personnel_private for select to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.user_station_assignments usa where usa.user_id=personnel_private.user_id and private.has_permission_in_scope('personnel.view_sensitive',usa.station_id,null)));
